// <auto-generated />
using System;
using APIFORD.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace APIFORD.Migrations
{
    [DbContext(typeof(FordDbContext))]
    [Migration("20260902221016_notificacoes")]
    partial class notificacoes
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.5")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("APIFORD.Model.CarroClasses.Carro", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("Ano")
                        .HasColumnType("integer")
                        .HasColumnName("ano");

                    b.Property<DateTime>("DataCriacao")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("data_criacao");

                    b.Property<bool>("Excluido")
                        .HasColumnType("boolean")
                        .HasColumnName("excluido");

                    b.Property<int>("LinhagemId")
                        .HasColumnType("integer")
                        .HasColumnName("linhagem_id");

                    b.Property<string>("Marca")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("marca");

                    b.Property<string>("Modelo")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("modelo");

                    b.Property<int?>("VersaoAnteriorId")
                        .HasColumnType("integer")
                        .HasColumnName("versao_anterior_id");

                    b.HasKey("Id")
                        .HasName("pk_carros");

                    b.ToTable("carros", (string)null);
                });

            modelBuilder.Entity("APIFORD.Model.CarroClasses.Fonte", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<decimal>("Confiabilidade")
                        .HasColumnType("numeric")
                        .HasColumnName("confiabilidade");

                    b.Property<DateTime>("DataAdicao")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("data_adicao");

                    b.Property<bool>("Excluido")
                        .HasColumnType("boolean")
                        .HasColumnName("excluido");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("nome");

                    b.Property<string>("Url")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("url");

                    b.HasKey("Id")
                        .HasName("pk_fontes");

                    b.ToTable("fontes", (string)null);
                });

            modelBuilder.Entity("APIFORD.Model.ComparacaoSalva", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("DataSalvamento")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("data_salvamento");

                    b.Property<string>("RequestPayload")
                        .IsRequired()
                        .HasColumnType("jsonb")
                        .HasColumnName("request_payload");

                    b.Property<string>("Tipo")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("tipo");

                    b.Property<string>("Titulo")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("character varying(150)")
                        .HasColumnName("titulo");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasMaxLength(450)
                        .HasColumnType("character varying(450)")
                        .HasColumnName("user_id");

                    b.HasKey("Id")
                        .HasName("pk_comparacoes_salvas");

                    b.HasIndex("UserId")
                        .HasDatabaseName("ix_comparacoes_salvas_user_id");

                    b.ToTable("comparacoes_salvas", (string)null);
                });

            modelBuilder.Entity("APIFORD.Model.Job", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id")
                        .HasDefaultValueSql("gen_random_uuid()");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.Property<string>("Error")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasColumnName("error");

                    b.Property<string>("Payload")
                        .IsRequired()
                        .HasColumnType("jsonb")
                        .HasColumnName("payload");

                    b.Property<string>("Result")
                        .HasColumnType("jsonb")
                        .HasColumnName("result");

                    b.Property<string>("Status")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(10)
                        .HasColumnType("character varying(10)")
                        .HasDefaultValue("pending")
                        .HasColumnName("status");

                    b.Property<DateTime>("UpdatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.HasKey("Id")
                        .HasName("pk_jobs");

                    b.ToTable("jobs", (string)null);
                });

            modelBuilder.Entity("APIFORD.Model.ModeloSalvo", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("text")
                        .HasColumnName("user_id");

                    b.Property<int>("CarroId")
                        .HasColumnType("integer")
                        .HasColumnName("carro_id");

                    b.Property<DateTime>("DataSalvo")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("data_salvo");

                    b.HasKey("UserId", "CarroId")
                        .HasName("pk_modelo_salvos");

                    b.HasIndex("CarroId")
                        .HasDatabaseName("ix_modelo_salvos_carro_id");

                    b.ToTable("modelo_salvos", (string)null);
                });

            modelBuilder.Entity("APIFORD.Model.Notification.NotificacaoEvento", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("DataCriacao")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("data_criacao");

                    b.Property<bool>("Excluido")
                        .HasColumnType("boolean")
                        .HasColumnName("excluido");

                    b.Property<string>("Mensagem")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("mensagem");

                    b.Property<string>("Subtitulo")
                        .HasColumnType("text")
                        .HasColumnName("subtitulo");

                    b.Property<int>("Tipo")
                        .HasColumnType("integer")
                        .HasColumnName("tipo");

                    b.Property<string>("Titulo")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("titulo");

                    b.HasKey("Id")
                        .HasName("pk_notificacoes_eventos");

                    b.ToTable("notificacoes_eventos", (string)null);
                });

            modelBuilder.Entity("APIFORD.Model.Notification.NotificacaoUsuario", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateTime?>("DataLeitura")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("data_leitura");

                    b.Property<bool>("Lida")
                        .HasColumnType("boolean")
                        .HasColumnName("lida");

                    b.Property<int>("NotificacaoEventoId")
                        .HasColumnType("integer")
                        .HasColumnName("notificacao_evento_id");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("user_id");

                    b.HasKey("Id")
                        .HasName("pk_notificacoes_usuarios");

                    b.HasIndex("NotificacaoEventoId")
                        .HasDatabaseName("ix_notificacoes_usuarios_notificacao_evento_id");

                    b.HasIndex("UserId", "Lida")
                        .HasDatabaseName("ix_notificacoes_usuarios_user_lida");

                    b.ToTable("notificacoes_usuarios", (string)null);
                });

            modelBuilder.Entity("APIFORD.Model.User", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("text")
                        .HasColumnName("id");

                    b.Property<int>("AccessFailedCount")
                        .HasColumnType("integer")
                        .HasColumnName("access_failed_count");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("text")
                        .HasColumnName("concurrency_stamp");

                    b.Property<string>("Email")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)")
                        .HasColumnName("email");

                    b.Property<bool>("EmailConfirmed")
                        .HasColumnType("boolean")
                        .HasColumnName("email_confirmed");

                    b.Property<bool>("Excluido")
                        .HasColumnType("boolean")
                        .HasColumnName("excluido");

                    b.Property<bool>("LockoutEnabled")
                        .HasColumnType("boolean")
                        .HasColumnName("lockout_enabled");

                    b.Property<DateTimeOffset?>("LockoutEnd")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("lockout_end");

                    b.Property<string>("NormalizedEmail")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)")
                        .HasColumnName("normalized_email");

                    b.Property<string>("NormalizedUserName")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)")
                        .HasColumnName("normalized_user_name");

                    b.Property<string>("PasswordHash")
                        .HasColumnType("text")
                        .HasColumnName("password_hash");

                    b.Property<string>("PhoneNumber")
                        .HasColumnType("text")
                        .HasColumnName("phone_number");

                    b.Property<bool>("PhoneNumberConfirmed")
                        .HasColumnType("boolean")
                        .HasColumnName("phone_number_confirmed");

                    b.Property<string>("SecurityStamp")
                        .HasColumnType("text")
                        .HasColumnName("security_stamp");

                    b.Property<bool>("TwoFactorEnabled")
                        .HasColumnType("boolean")
                        .HasColumnName("two_factor_enabled");

                    b.Property<string>("UserName")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)")
                        .HasColumnName("user_name");

                    b.HasKey("Id")
                        .HasName("pk_asp_net_users");

                    b.HasIndex("NormalizedEmail")
                        .HasDatabaseName("EmailIndex");

                    b.HasIndex("NormalizedUserName")
                        .IsUnique()
                        .HasDatabaseName("UserNameIndex");

                    b.ToTable("AspNetUsers", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRole", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("text")
                        .HasColumnName("id");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("text")
                        .HasColumnName("concurrency_stamp");

                    b.Property<string>("Name")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)")
                        .HasColumnName("name");

                    b.Property<string>("NormalizedName")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)")
                        .HasColumnName("normalized_name");

                    b.HasKey("Id")
                        .HasName("pk_asp_net_roles");

                    b.HasIndex("NormalizedName")
                        .IsUnique()
                        .HasDatabaseName("RoleNameIndex");

                    b.ToTable("AspNetRoles", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<string>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("ClaimType")
                        .HasColumnType("text")
                        .HasColumnName("claim_type");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("text")
                        .HasColumnName("claim_value");

                    b.Property<string>("RoleId")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("role_id");

                    b.HasKey("Id")
                        .HasName("pk_asp_net_role_claims");

                    b.HasIndex("RoleId")
                        .HasDatabaseName("ix_asp_net_role_claims_role_id");

                    b.ToTable("AspNetRoleClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<string>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("ClaimType")
                        .HasColumnType("text")
                        .HasColumnName("claim_type");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("text")
                        .HasColumnName("claim_value");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("user_id");

                    b.HasKey("Id")
                        .HasName("pk_asp_net_user_claims");

                    b.HasIndex("UserId")
                        .HasDatabaseName("ix_asp_net_user_claims_user_id");

                    b.ToTable("AspNetUserClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<string>", b =>
                {
                    b.Property<string>("LoginProvider")
                        .HasColumnType("text")
                        .HasColumnName("login_provider");

                    b.Property<string>("ProviderKey")
                        .HasColumnType("text")
                        .HasColumnName("provider_key");

                    b.Property<string>("ProviderDisplayName")
                        .HasColumnType("text")
                        .HasColumnName("provider_display_name");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("user_id");

                    b.HasKey("LoginProvider", "ProviderKey")
                        .HasName("pk_asp_net_user_logins");

                    b.HasIndex("UserId")
                        .HasDatabaseName("ix_asp_net_user_logins_user_id");

                    b.ToTable("AspNetUserLogins", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<string>", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("text")
                        .HasColumnName("user_id");

                    b.Property<string>("RoleId")
                        .HasColumnType("text")
                        .HasColumnName("role_id");

                    b.HasKey("UserId", "RoleId")
                        .HasName("pk_asp_net_user_roles");

                    b.HasIndex("RoleId")
                        .HasDatabaseName("ix_asp_net_user_roles_role_id");

                    b.ToTable("AspNetUserRoles", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<string>", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("text")
                        .HasColumnName("user_id");

                    b.Property<string>("LoginProvider")
                        .HasColumnType("text")
                        .HasColumnName("login_provider");

                    b.Property<string>("Name")
                        .HasColumnType("text")
                        .HasColumnName("name");

                    b.Property<string>("Value")
                        .HasColumnType("text")
                        .HasColumnName("value");

                    b.HasKey("UserId", "LoginProvider", "Name")
                        .HasName("pk_asp_net_user_tokens");

                    b.ToTable("AspNetUserTokens", (string)null);
                });

            modelBuilder.Entity("APIFORD.Model.CarroClasses.Carro", b =>
                {
                    b.OwnsOne("PropriedadeScraping", "Categoria", b1 =>
                        {
                            b1.Property<int>("CarroId");

                            b1.Property<double>("Confianca");

                            b1.Property<bool>("Conflito");

                            b1.HasKey("CarroId")
                                .HasName("pk_carros");

                            b1.ToTable("carros");

                            b1
                                .ToJson("categoria")
                                .HasColumnType("jsonb");

                            b1.WithOwner()
                                .HasForeignKey("CarroId")
                                .HasConstraintName("fk_carros_carros_carro_id");

                            b1.OwnsMany("ItemFonteScraping", "Fontes", b2 =>
                                {
                                    b2.Property<int>("PropriedadeScrapingCarroId");

                                    b2.Property<int>("__synthesizedOrdinal")
                                        .ValueGeneratedOnAdd();

                                    b2.Property<double>("Confianca");

                                    b2.Property<DateTime>("DataColeta");

                                    b2.Property<DateTime?>("DataReferencia");

                                    b2.Property<string>("Fonte")
                                        .IsRequired();

                                    b2.Property<int>("FonteId");

                                    b2.Property<string>("Valor");

                                    b2.HasKey("PropriedadeScrapingCarroId", "__synthesizedOrdinal")
                                        .HasName("pk_carros");

                                    b2.ToTable("carros");

                                    b2.WithOwner()
                                        .HasForeignKey("PropriedadeScrapingCarroId")
                                        .HasConstraintName("fk_carros_carros_propriedade_scraping_carro_id");
                                });

                            b1.Navigation("Fontes");
                        });

                    b.OwnsMany("APIFORD.Model.CarroClasses.Consumo", "Consumos", b1 =>
                        {
                            b1.Property<int>("CarroId");

                            b1.Property<int>("__synthesizedOrdinal")
                                .ValueGeneratedOnAdd();

                            b1.Property<DateTime>("DataColeta");

                            b1.HasKey("CarroId", "__synthesizedOrdinal");

                            b1.ToTable("carros");

                            b1
                                .ToJson("consumos")
                                .HasColumnType("jsonb");

                            b1.WithOwner()
                                .HasForeignKey("CarroId")
                                .HasConstraintName("fk_carros_carros_carro_id");

                            b1.OwnsOne("PropriedadeScraping", "Cidade", b2 =>
                                {
                                    b2.Property<int>("ConsumoCarroId");

                                    b2.Property<int>("Consumo__synthesizedOrdinal");

                                    b2.Property<double>("Confianca");

                                    b2.Property<bool>("Conflito");

                                    b2.HasKey("ConsumoCarroId", "Consumo__synthesizedOrdinal")
                                        .HasName("pk_carros");

                                    b2.ToTable("carros");

                                    b2.WithOwner()
                                        .HasForeignKey("ConsumoCarroId", "Consumo__synthesizedOrdinal")
                                        .HasConstraintName("fk_carros_carros_consumo_carro_id_consumo__synthesized_ordinal");

                                    b2.OwnsMany("ItemFonteScraping", "Fontes", b3 =>
                                        {
                                            b3.Property<int>("PropriedadeScrapingConsumoCarroId");

                                            b3.Property<int>("PropriedadeScrapingConsumo__synthesizedOrdinal");

                                            b3.Property<int>("__synthesizedOrdinal")
                                                .ValueGeneratedOnAdd();

                                            b3.Property<double>("Confianca");

                                            b3.Property<DateTime>("DataColeta");

                                            b3.Property<DateTime?>("DataReferencia");

                                            b3.Property<string>("Fonte")
                                                .IsRequired();

                                            b3.Property<int>("FonteId");

                                            b3.Property<decimal>("Valor");

                                            b3.HasKey("PropriedadeScrapingConsumoCarroId", "PropriedadeScrapingConsumo__synthesizedOrdinal", "__synthesizedOrdinal")
                                                .HasName("pk_carros");

                                            b3.ToTable("carros");

                                            b3.WithOwner()
                                                .HasForeignKey("PropriedadeScrapingConsumoCarroId", "PropriedadeScrapingConsumo__synthesizedOrdinal")
                                                .HasConstraintName("fk_carros_carros_propriedade_scraping_consumo_carro_id_propriedade");
                                        });

                                    b2.Navigation("Fontes");
                                });

                            b1.OwnsOne("APIFORD.Model.CarroClasses.PropriedadeScraping<decimal>", "Estrada", b2 =>
                                {
                                    b2.Property<int>("ConsumoCarroId");

                                    b2.Property<int>("Consumo__synthesizedOrdinal");

                                    b2.Property<double>("Confianca");

                                    b2.Property<bool>("Conflito");

                                    b2.HasKey("ConsumoCarroId", "Consumo__synthesizedOrdinal")
                                        .HasName("pk_carros");

                                    b2.ToTable("carros");

                                    b2.WithOwner()
                                        .HasForeignKey("ConsumoCarroId", "Consumo__synthesizedOrdinal")
                                        .HasConstraintName("fk_carros_carros_consumo_carro_id_consumo__synthesized_ordinal");

                                    b2.OwnsMany("APIFORD.Model.CarroClasses.ItemFonteScraping<decimal>", "Fontes", b3 =>
                                        {
                                            b3.Property<int>("PropriedadeScraping<decimal>ConsumoCarroId");

                                            b3.Property<int>("PropriedadeScraping<decimal>Consumo__synthesizedOrdinal");

                                            b3.Property<int>("__synthesizedOrdinal")
                                                .ValueGeneratedOnAdd();

                                            b3.Property<double>("Confianca");

                                            b3.Property<DateTime>("DataColeta");

                                            b3.Property<DateTime?>("DataReferencia");

                                            b3.Property<string>("Fonte")
                                                .IsRequired();

                                            b3.Property<int>("FonteId");

                                            b3.Property<decimal>("Valor");

                                            b3.HasKey("PropriedadeScraping<decimal>ConsumoCarroId", "PropriedadeScraping<decimal>Consumo__synthesizedOrdinal", "__synthesizedOrdinal")
                                                .HasName("pk_carros");

                                            b3.ToTable("carros");

                                            b3.WithOwner()
                                                .HasForeignKey("PropriedadeScraping<decimal>ConsumoCarroId", "PropriedadeScraping<decimal>Consumo__synthesizedOrdinal")
                                                .HasConstraintName("fk_carros_carros_propriedade_scraping_decimal_consumo_carro_id_pr");
                                        });

                                    b2.Navigation("Fontes");
                                });

                            b1.Navigation("Cidade")
                                .IsRequired();

                            b1.Navigation("Estrada")
                                .IsRequired();
                        });

                    b.OwnsMany("APIFORD.Model.CarroClasses.Dimensao", "Dimensoes", b1 =>
                        {
                            b1.Property<int>("CarroId");

                            b1.Property<int>("__synthesizedOrdinal")
                                .ValueGeneratedOnAdd();

                            b1.Property<DateTime>("DataColeta");

                            b1.HasKey("CarroId", "__synthesizedOrdinal");

                            b1.ToTable("carros");

                            b1
                                .ToJson("dimensoes")
                                .HasColumnType("jsonb");

                            b1.WithOwner()
                                .HasForeignKey("CarroId")
                                .HasConstraintName("fk_carros_carros_carro_id");

                            b1.OwnsOne("APIFORD.Model.CarroClasses.PropriedadeScraping<decimal>", "Altura", b2 =>
                                {
                                    b2.Property<int>("DimensaoCarroId");

                                    b2.Property<int>("Dimensao__synthesizedOrdinal");

                                    b2.Property<double>("Confianca");

                                    b2.Property<bool>("Conflito");

                                    b2.HasKey("DimensaoCarroId", "Dimensao__synthesizedOrdinal")
                                        .HasName("pk_carros");

                                    b2.ToTable("carros");

                                    b2.WithOwner()
                                        .HasForeignKey("DimensaoCarroId", "Dimensao__synthesizedOrdinal")
                                        .HasConstraintName("fk_carros_carros_dimensao_carro_id_dimensao__synthesized_ordinal");

                                    b2.OwnsMany("APIFORD.Model.CarroClasses.ItemFonteScraping<decimal>", "Fontes", b3 =>
                                        {
                                            b3.Property<int>("PropriedadeScraping<decimal>DimensaoCarroId");

                                            b3.Property<int>("PropriedadeScraping<decimal>Dimensao__synthesizedOrdinal");

                                            b3.Property<int>("__synthesizedOrdinal")
                                                .ValueGeneratedOnAdd();

                                            b3.Property<double>("Confianca");

                                            b3.Property<DateTime>("DataColeta");

                                            b3.Property<DateTime?>("DataReferencia");

                                            b3.Property<string>("Fonte")
                                                .IsRequired();

                                            b3.Property<int>("FonteId");

                                            b3.Property<decimal>("Valor");

                                            b3.HasKey("PropriedadeScraping<decimal>DimensaoCarroId", "PropriedadeScraping<decimal>Dimensao__synthesizedOrdinal", "__synthesizedOrdinal")
                                                .HasName("pk_carros");

                                            b3.ToTable("carros");

                                            b3.WithOwner()
                                                .HasForeignKey("PropriedadeScraping<decimal>DimensaoCarroId", "PropriedadeScraping<decimal>Dimensao__synthesizedOrdinal")
                                                .HasConstraintName("fk_carros_carros_propriedade_scraping_decimal_dimensao_carro_id_p");
                                        });

                                    b2.Navigation("Fontes");
                                });

                            b1.OwnsOne("APIFORD.Model.CarroClasses.PropriedadeScraping<decimal>", "Comprimento", b2 =>
                                {
                                    b2.Property<int>("DimensaoCarroId");

                                    b2.Property<int>("Dimensao__synthesizedOrdinal");

                                    b2.Property<double>("Confianca");

                                    b2.Property<bool>("Conflito");

                                    b2.HasKey("DimensaoCarroId", "Dimensao__synthesizedOrdinal")
                                        .HasName("pk_carros");

                                    b2.ToTable("carros");

                                    b2.WithOwner()
                                        .HasForeignKey("DimensaoCarroId", "Dimensao__synthesizedOrdinal")
                                        .HasConstraintName("fk_carros_carros_dimensao_carro_id_dimensao__synthesized_ordinal");

                                    b2.OwnsMany("APIFORD.Model.CarroClasses.ItemFonteScraping<decimal>", "Fontes", b3 =>
                                        {
                                            b3.Property<int>("PropriedadeScraping<decimal>DimensaoCarroId");

                                            b3.Property<int>("PropriedadeScraping<decimal>Dimensao__synthesizedOrdinal");

                                            b3.Property<int>("__synthesizedOrdinal")
                                                .ValueGeneratedOnAdd();

                                            b3.Property<double>("Confianca");

                                            b3.Property<DateTime>("DataColeta");

                                            b3.Property<DateTime?>("DataReferencia");

                                            b3.Property<string>("Fonte")
                                                .IsRequired();

                                            b3.Property<int>("FonteId");

                                            b3.Property<decimal>("Valor");

                                            b3.HasKey("PropriedadeScraping<decimal>DimensaoCarroId", "PropriedadeScraping<decimal>Dimensao__synthesizedOrdinal", "__synthesizedOrdinal")
                                                .HasName("pk_carros");

                                            b3.ToTable("carros");

                                            b3.WithOwner()
                                                .HasForeignKey("PropriedadeScraping<decimal>DimensaoCarroId", "PropriedadeScraping<decimal>Dimensao__synthesizedOrdinal")
                                                .HasConstraintName("fk_carros_carros_propriedade_scraping_decimal_dimensao_carro_id_p");
                                        });

                                    b2.Navigation("Fontes");
                                });

                            b1.OwnsOne("APIFORD.Model.CarroClasses.PropriedadeScraping<decimal>", "EntreEixos", b2 =>
                                {
                                    b2.Property<int>("DimensaoCarroId");

                                    b2.Property<int>("Dimensao__synthesizedOrdinal");

                                    b2.Property<double>("Confianca");

                                    b2.Property<bool>("Conflito");

                                    b2.HasKey("DimensaoCarroId", "Dimensao__synthesizedOrdinal")
                                        .HasName("pk_carros");

                                    b2.ToTable("carros");

                                    b2.WithOwner()
                                        .HasForeignKey("DimensaoCarroId", "Dimensao__synthesizedOrdinal")
                                        .HasConstraintName("fk_carros_carros_dimensao_carro_id_dimensao__synthesized_ordinal");

                                    b2.OwnsMany("APIFORD.Model.CarroClasses.ItemFonteScraping<decimal>", "Fontes", b3 =>
                                        {
                                            b3.Property<int>("PropriedadeScraping<decimal>DimensaoCarroId");

                                            b3.Property<int>("PropriedadeScraping<decimal>Dimensao__synthesizedOrdinal");

                                            b3.Property<int>("__synthesizedOrdinal")
                                                .ValueGeneratedOnAdd();

                                            b3.Property<double>("Confianca");

                                            b3.Property<DateTime>("DataColeta");

                                            b3.Property<DateTime?>("DataReferencia");

                                            b3.Property<string>("Fonte")
                                                .IsRequired();

                                            b3.Property<int>("FonteId");

                                            b3.Property<decimal>("Valor");

                                            b3.HasKey("PropriedadeScraping<decimal>DimensaoCarroId", "PropriedadeScraping<decimal>Dimensao__synthesizedOrdinal", "__synthesizedOrdinal")
                                                .HasName("pk_carros");

                                            b3.ToTable("carros");

                                            b3.WithOwner()
                                                .HasForeignKey("PropriedadeScraping<decimal>DimensaoCarroId", "PropriedadeScraping<decimal>Dimensao__synthesizedOrdinal")
                                                .HasConstraintName("fk_carros_carros_propriedade_scraping_decimal_dimensao_carro_id_p");
                                        });

                                    b2.Navigation("Fontes");
                                });

                            b1.OwnsOne("APIFORD.Model.CarroClasses.PropriedadeScraping<decimal>", "Largura", b2 =>
                                {
                                    b2.Property<int>("DimensaoCarroId");

                                    b2.Property<int>("Dimensao__synthesizedOrdinal");

                                    b2.Property<double>("Confianca");

                                    b2.Property<bool>("Conflito");

                                    b2.HasKey("DimensaoCarroId", "Dimensao__synthesizedOrdinal")
                                        .HasName("pk_carros");

                                    b2.ToTable("carros");

                                    b2.WithOwner()
                                        .HasForeignKey("DimensaoCarroId", "Dimensao__synthesizedOrdinal")
                                        .HasConstraintName("fk_carros_carros_dimensao_carro_id_dimensao__synthesized_ordinal");

                                    b2.OwnsMany("APIFORD.Model.CarroClasses.ItemFonteScraping<decimal>", "Fontes", b3 =>
                                        {
                                            b3.Property<int>("PropriedadeScraping<decimal>DimensaoCarroId");

                                            b3.Property<int>("PropriedadeScraping<decimal>Dimensao__synthesizedOrdinal");

                                            b3.Property<int>("__synthesizedOrdinal")
                                                .ValueGeneratedOnAdd();

                                            b3.Property<double>("Confianca");

                                            b3.Property<DateTime>("DataColeta");

                                            b3.Property<DateTime?>("DataReferencia");

                                            b3.Property<string>("Fonte")
                                                .IsRequired();

                                            b3.Property<int>("FonteId");

                                            b3.Property<decimal>("Valor");

                                            b3.HasKey("PropriedadeScraping<decimal>DimensaoCarroId", "PropriedadeScraping<decimal>Dimensao__synthesizedOrdinal", "__synthesizedOrdinal")
                                                .HasName("pk_carros");

                                            b3.ToTable("carros");

                                            b3.WithOwner()
                                                .HasForeignKey("PropriedadeScraping<decimal>DimensaoCarroId", "PropriedadeScraping<decimal>Dimensao__synthesizedOrdinal")
                                                .HasConstraintName("fk_carros_carros_propriedade_scraping_decimal_dimensao_carro_id_p");
                                        });

                                    b2.Navigation("Fontes");
                                });

                            b1.Navigation("Altura")
                                .IsRequired();

                            b1.Navigation("Comprimento")
                                .IsRequired();

                            b1.Navigation("EntreEixos")
                                .IsRequired();

                            b1.Navigation("Largura")
                                .IsRequired();
                        });

                    b.OwnsMany("APIFORD.Model.CarroClasses.Especificacao", "Especificacoes", b1 =>
                        {
                            b1.Property<int>("CarroId");

                            b1.Property<int>("__synthesizedOrdinal")
                                .ValueGeneratedOnAdd();

                            b1.Property<DateTime>("DataColeta");

                            b1.HasKey("CarroId", "__synthesizedOrdinal");

                            b1.ToTable("carros");

                            b1
                                .ToJson("especificacoes")
                                .HasColumnType("jsonb");

                            b1.WithOwner()
                                .HasForeignKey("CarroId")
                                .HasConstraintName("fk_carros_carros_carro_id");

                            b1.OwnsOne("PropriedadeScraping", "Potencia", b2 =>
                                {
                                    b2.Property<int>("EspecificacaoCarroId");

                                    b2.Property<int>("Especificacao__synthesizedOrdinal");

                                    b2.Property<double>("Confianca");

                                    b2.Property<bool>("Conflito");

                                    b2.HasKey("EspecificacaoCarroId", "Especificacao__synthesizedOrdinal")
                                        .HasName("pk_carros");

                                    b2.ToTable("carros");

                                    b2.WithOwner()
                                        .HasForeignKey("EspecificacaoCarroId", "Especificacao__synthesizedOrdinal")
                                        .HasConstraintName("fk_carros_carros_especificacao_carro_id_especificacao__synthesiz");

                                    b2.OwnsMany("ItemFonteScraping", "Fontes", b3 =>
                                        {
                                            b3.Property<int>("PropriedadeScrapingEspecificacaoCarroId");

                                            b3.Property<int>("PropriedadeScrapingEspecificacao__synthesizedOrdinal");

                                            b3.Property<int>("__synthesizedOrdinal")
                                                .ValueGeneratedOnAdd();

                                            b3.Property<double>("Confianca");

                                            b3.Property<DateTime>("DataColeta");

                                            b3.Property<DateTime?>("DataReferencia");

                                            b3.Property<string>("Fonte")
                                                .IsRequired();

                                            b3.Property<int>("FonteId");

                                            b3.Property<int>("Valor");

                                            b3.HasKey("PropriedadeScrapingEspecificacaoCarroId", "PropriedadeScrapingEspecificacao__synthesizedOrdinal", "__synthesizedOrdinal")
                                                .HasName("pk_carros");

                                            b3.ToTable("carros");

                                            b3.WithOwner()
                                                .HasForeignKey("PropriedadeScrapingEspecificacaoCarroId", "PropriedadeScrapingEspecificacao__synthesizedOrdinal")
                                                .HasConstraintName("fk_carros_carros_propriedade_scraping_especificacao_carro_id_propr");
                                        });

                                    b2.Navigation("Fontes");
                                });

                            b1.OwnsOne("APIFORD.Model.CarroClasses.PropriedadeScraping<int>", "PotenciaRpm", b2 =>
                                {
                                    b2.Property<int>("EspecificacaoCarroId");

                                    b2.Property<int>("Especificacao__synthesizedOrdinal");

                                    b2.Property<double>("Confianca");

                                    b2.Property<bool>("Conflito");

                                    b2.HasKey("EspecificacaoCarroId", "Especificacao__synthesizedOrdinal")
                                        .HasName("pk_carros");

                                    b2.ToTable("carros");

                                    b2.WithOwner()
                                        .HasForeignKey("EspecificacaoCarroId", "Especificacao__synthesizedOrdinal")
                                        .HasConstraintName("fk_carros_carros_especificacao_carro_id_especificacao__synthesiz");

                                    b2.OwnsMany("APIFORD.Model.CarroClasses.ItemFonteScraping<int>", "Fontes", b3 =>
                                        {
                                            b3.Property<int>("PropriedadeScraping<int>EspecificacaoCarroId");

                                            b3.Property<int>("PropriedadeScraping<int>Especificacao__synthesizedOrdinal");

                                            b3.Property<int>("__synthesizedOrdinal")
                                                .ValueGeneratedOnAdd();

                                            b3.Property<double>("Confianca");

                                            b3.Property<DateTime>("DataColeta");

                                            b3.Property<DateTime?>("DataReferencia");

                                            b3.Property<string>("Fonte")
                                                .IsRequired();

                                            b3.Property<int>("FonteId");

                                            b3.Property<int>("Valor");

                                            b3.HasKey("PropriedadeScraping<int>EspecificacaoCarroId", "PropriedadeScraping<int>Especificacao__synthesizedOrdinal", "__synthesizedOrdinal")
                                                .HasName("pk_carros");

                                            b3.ToTable("carros");

                                            b3.WithOwner()
                                                .HasForeignKey("PropriedadeScraping<int>EspecificacaoCarroId", "PropriedadeScraping<int>Especificacao__synthesizedOrdinal")
                                                .HasConstraintName("fk_carros_carros_propriedade_scraping_int_especificacao_carro_id_");
                                        });

                                    b2.Navigation("Fontes");
                                });

                            b1.OwnsOne("APIFORD.Model.CarroClasses.PropriedadeScraping<int>", "Torque", b2 =>
                                {
                                    b2.Property<int>("EspecificacaoCarroId");

                                    b2.Property<int>("Especificacao__synthesizedOrdinal");

                                    b2.Property<double>("Confianca");

                                    b2.Property<bool>("Conflito");

                                    b2.HasKey("EspecificacaoCarroId", "Especificacao__synthesizedOrdinal")
                                        .HasName("pk_carros");

                                    b2.ToTable("carros");

                                    b2.WithOwner()
                                        .HasForeignKey("EspecificacaoCarroId", "Especificacao__synthesizedOrdinal")
                                        .HasConstraintName("fk_carros_carros_especificacao_carro_id_especificacao__synthesiz");

                                    b2.OwnsMany("APIFORD.Model.CarroClasses.ItemFonteScraping<int>", "Fontes", b3 =>
                                        {
                                            b3.Property<int>("PropriedadeScraping<int>EspecificacaoCarroId");

                                            b3.Property<int>("PropriedadeScraping<int>Especificacao__synthesizedOrdinal");

                                            b3.Property<int>("__synthesizedOrdinal")
                                                .ValueGeneratedOnAdd();

                                            b3.Property<double>("Confianca");

                                            b3.Property<DateTime>("DataColeta");

                                            b3.Property<DateTime?>("DataReferencia");

                                            b3.Property<string>("Fonte")
                                                .IsRequired();

                                            b3.Property<int>("FonteId");

                                            b3.Property<int>("Valor");

                                            b3.HasKey("PropriedadeScraping<int>EspecificacaoCarroId", "PropriedadeScraping<int>Especificacao__synthesizedOrdinal", "__synthesizedOrdinal")
                                                .HasName("pk_carros");

                                            b3.ToTable("carros");

                                            b3.WithOwner()
                                                .HasForeignKey("PropriedadeScraping<int>EspecificacaoCarroId", "PropriedadeScraping<int>Especificacao__synthesizedOrdinal")
                                                .HasConstraintName("fk_carros_carros_propriedade_scraping_int_especificacao_carro_id_");
                                        });

                                    b2.Navigation("Fontes");
                                });

                            b1.OwnsOne("APIFORD.Model.CarroClasses.PropriedadeScraping<int>", "TorqueRpm", b2 =>
                                {
                                    b2.Property<int>("EspecificacaoCarroId");

                                    b2.Property<int>("Especificacao__synthesizedOrdinal");

                                    b2.Property<double>("Confianca");

                                    b2.Property<bool>("Conflito");

                                    b2.HasKey("EspecificacaoCarroId", "Especificacao__synthesizedOrdinal")
                                        .HasName("pk_carros");

                                    b2.ToTable("carros");

                                    b2.WithOwner()
                                        .HasForeignKey("EspecificacaoCarroId", "Especificacao__synthesizedOrdinal")
                                        .HasConstraintName("fk_carros_carros_especificacao_carro_id_especificacao__synthesiz");

                                    b2.OwnsMany("APIFORD.Model.CarroClasses.ItemFonteScraping<int>", "Fontes", b3 =>
                                        {
                                            b3.Property<int>("PropriedadeScraping<int>EspecificacaoCarroId");

                                            b3.Property<int>("PropriedadeScraping<int>Especificacao__synthesizedOrdinal");

                                            b3.Property<int>("__synthesizedOrdinal")
                                                .ValueGeneratedOnAdd();

                                            b3.Property<double>("Confianca");

                                            b3.Property<DateTime>("DataColeta");

                                            b3.Property<DateTime?>("DataReferencia");

                                            b3.Property<string>("Fonte")
                                                .IsRequired();

                                            b3.Property<int>("FonteId");

                                            b3.Property<int>("Valor");

                                            b3.HasKey("PropriedadeScraping<int>EspecificacaoCarroId", "PropriedadeScraping<int>Especificacao__synthesizedOrdinal", "__synthesizedOrdinal")
                                                .HasName("pk_carros");

                                            b3.ToTable("carros");

                                            b3.WithOwner()
                                                .HasForeignKey("PropriedadeScraping<int>EspecificacaoCarroId", "PropriedadeScraping<int>Especificacao__synthesizedOrdinal")
                                                .HasConstraintName("fk_carros_carros_propriedade_scraping_int_especificacao_carro_id_");
                                        });

                                    b2.Navigation("Fontes");
                                });

                            b1.OwnsOne("APIFORD.Model.CarroClasses.PropriedadeScraping<string>", "Tracao", b2 =>
                                {
                                    b2.Property<int>("EspecificacaoCarroId");

                                    b2.Property<int>("Especificacao__synthesizedOrdinal");

                                    b2.Property<double>("Confianca");

                                    b2.Property<bool>("Conflito");

                                    b2.HasKey("EspecificacaoCarroId", "Especificacao__synthesizedOrdinal")
                                        .HasName("pk_carros");

                                    b2.ToTable("carros");

                                    b2.WithOwner()
                                        .HasForeignKey("EspecificacaoCarroId", "Especificacao__synthesizedOrdinal")
                                        .HasConstraintName("fk_carros_carros_especificacao_carro_id_especificacao__synthesiz");

                                    b2.OwnsMany("APIFORD.Model.CarroClasses.ItemFonteScraping<string>", "Fontes", b3 =>
                                        {
                                            b3.Property<int>("PropriedadeScraping<string>EspecificacaoCarroId");

                                            b3.Property<int>("PropriedadeScraping<string>Especificacao__synthesizedOrdinal");

                                            b3.Property<int>("__synthesizedOrdinal")
                                                .ValueGeneratedOnAdd();

                                            b3.Property<double>("Confianca");

                                            b3.Property<DateTime>("DataColeta");

                                            b3.Property<DateTime?>("DataReferencia");

                                            b3.Property<string>("Fonte")
                                                .IsRequired();

                                            b3.Property<int>("FonteId");

                                            b3.Property<string>("Valor");

                                            b3.HasKey("PropriedadeScraping<string>EspecificacaoCarroId", "PropriedadeScraping<string>Especificacao__synthesizedOrdinal", "__synthesizedOrdinal")
                                                .HasName("pk_carros");

                                            b3.ToTable("carros");

                                            b3.WithOwner()
                                                .HasForeignKey("PropriedadeScraping<string>EspecificacaoCarroId", "PropriedadeScraping<string>Especificacao__synthesizedOrdinal")
                                                .HasConstraintName("fk_carros_carros_propriedade_scraping_string_especificacao_carro");
                                        });

                                    b2.Navigation("Fontes");
                                });

                            b1.OwnsOne("APIFORD.Model.CarroClasses.PropriedadeScraping<string>", "Transmissao", b2 =>
                                {
                                    b2.Property<int>("EspecificacaoCarroId");

                                    b2.Property<int>("Especificacao__synthesizedOrdinal");

                                    b2.Property<double>("Confianca");

                                    b2.Property<bool>("Conflito");

                                    b2.HasKey("EspecificacaoCarroId", "Especificacao__synthesizedOrdinal")
                                        .HasName("pk_carros");

                                    b2.ToTable("carros");

                                    b2.WithOwner()
                                        .HasForeignKey("EspecificacaoCarroId", "Especificacao__synthesizedOrdinal")
                                        .HasConstraintName("fk_carros_carros_especificacao_carro_id_especificacao__synthesiz");

                                    b2.OwnsMany("APIFORD.Model.CarroClasses.ItemFonteScraping<string>", "Fontes", b3 =>
                                        {
                                            b3.Property<int>("PropriedadeScraping<string>EspecificacaoCarroId");

                                            b3.Property<int>("PropriedadeScraping<string>Especificacao__synthesizedOrdinal");

                                            b3.Property<int>("__synthesizedOrdinal")
                                                .ValueGeneratedOnAdd();

                                            b3.Property<double>("Confianca");

                                            b3.Property<DateTime>("DataColeta");

                                            b3.Property<DateTime?>("DataReferencia");

                                            b3.Property<string>("Fonte")
                                                .IsRequired();

                                            b3.Property<int>("FonteId");

                                            b3.Property<string>("Valor");

                                            b3.HasKey("PropriedadeScraping<string>EspecificacaoCarroId", "PropriedadeScraping<string>Especificacao__synthesizedOrdinal", "__synthesizedOrdinal")
                                                .HasName("pk_carros");

                                            b3.ToTable("carros");

                                            b3.WithOwner()
                                                .HasForeignKey("PropriedadeScraping<string>EspecificacaoCarroId", "PropriedadeScraping<string>Especificacao__synthesizedOrdinal")
                                                .HasConstraintName("fk_carros_carros_propriedade_scraping_string_especificacao_carro");
                                        });

                                    b2.Navigation("Fontes");
                                });

                            b1.Navigation("Potencia")
                                .IsRequired();

                            b1.Navigation("PotenciaRpm")
                                .IsRequired();

                            b1.Navigation("Torque")
                                .IsRequired();

                            b1.Navigation("TorqueRpm")
                                .IsRequired();

                            b1.Navigation("Tracao")
                                .IsRequired();

                            b1.Navigation("Transmissao")
                                .IsRequired();
                        });

                    b.OwnsMany("APIFORD.Model.CarroClasses.Extra", "Extras", b1 =>
                        {
                            b1.Property<int>("CarroId");

                            b1.Property<int>("__synthesizedOrdinal")
                                .ValueGeneratedOnAdd();

                            b1.Property<DateTime>("DataColeta");

                            b1.HasKey("CarroId", "__synthesizedOrdinal");

                            b1.ToTable("carros");

                            b1
                                .ToJson("extras")
                                .HasColumnType("jsonb");

                            b1.WithOwner()
                                .HasForeignKey("CarroId")
                                .HasConstraintName("fk_carros_carros_carro_id");

                            b1.OwnsOne("APIFORD.Model.CarroClasses.PropriedadeScraping<decimal>", "CapacidadeCarga", b2 =>
                                {
                                    b2.Property<int>("ExtraCarroId");

                                    b2.Property<int>("Extra__synthesizedOrdinal");

                                    b2.Property<double>("Confianca");

                                    b2.Property<bool>("Conflito");

                                    b2.HasKey("ExtraCarroId", "Extra__synthesizedOrdinal")
                                        .HasName("pk_carros");

                                    b2.ToTable("carros");

                                    b2.WithOwner()
                                        .HasForeignKey("ExtraCarroId", "Extra__synthesizedOrdinal")
                                        .HasConstraintName("fk_carros_carros_extra_carro_id_extra__synthesized_ordinal");

                                    b2.OwnsMany("APIFORD.Model.CarroClasses.ItemFonteScraping<decimal>", "Fontes", b3 =>
                                        {
                                            b3.Property<int>("PropriedadeScraping<decimal>ExtraCarroId");

                                            b3.Property<int>("PropriedadeScraping<decimal>Extra__synthesizedOrdinal");

                                            b3.Property<int>("__synthesizedOrdinal")
                                                .ValueGeneratedOnAdd();

                                            b3.Property<double>("Confianca");

                                            b3.Property<DateTime>("DataColeta");

                                            b3.Property<DateTime?>("DataReferencia");

                                            b3.Property<string>("Fonte")
                                                .IsRequired();

                                            b3.Property<int>("FonteId");

                                            b3.Property<decimal>("Valor");

                                            b3.HasKey("PropriedadeScraping<decimal>ExtraCarroId", "PropriedadeScraping<decimal>Extra__synthesizedOrdinal", "__synthesizedOrdinal")
                                                .HasName("pk_carros");

                                            b3.ToTable("carros");

                                            b3.WithOwner()
                                                .HasForeignKey("PropriedadeScraping<decimal>ExtraCarroId", "PropriedadeScraping<decimal>Extra__synthesizedOrdinal")
                                                .HasConstraintName("fk_carros_carros_propriedade_scraping_decimal_extra_carro_id_prop");
                                        });

                                    b2.Navigation("Fontes");
                                });

                            b1.OwnsOne("APIFORD.Model.CarroClasses.PropriedadeScraping<decimal>", "CapacidadeReboque", b2 =>
                                {
                                    b2.Property<int>("ExtraCarroId");

                                    b2.Property<int>("Extra__synthesizedOrdinal");

                                    b2.Property<double>("Confianca");

                                    b2.Property<bool>("Conflito");

                                    b2.HasKey("ExtraCarroId", "Extra__synthesizedOrdinal")
                                        .HasName("pk_carros");

                                    b2.ToTable("carros");

                                    b2.WithOwner()
                                        .HasForeignKey("ExtraCarroId", "Extra__synthesizedOrdinal")
                                        .HasConstraintName("fk_carros_carros_extra_carro_id_extra__synthesized_ordinal");

                                    b2.OwnsMany("APIFORD.Model.CarroClasses.ItemFonteScraping<decimal>", "Fontes", b3 =>
                                        {
                                            b3.Property<int>("PropriedadeScraping<decimal>ExtraCarroId");

                                            b3.Property<int>("PropriedadeScraping<decimal>Extra__synthesizedOrdinal");

                                            b3.Property<int>("__synthesizedOrdinal")
                                                .ValueGeneratedOnAdd();

                                            b3.Property<double>("Confianca");

                                            b3.Property<DateTime>("DataColeta");

                                            b3.Property<DateTime?>("DataReferencia");

                                            b3.Property<string>("Fonte")
                                                .IsRequired();

                                            b3.Property<int>("FonteId");

                                            b3.Property<decimal>("Valor");

                                            b3.HasKey("PropriedadeScraping<decimal>ExtraCarroId", "PropriedadeScraping<decimal>Extra__synthesizedOrdinal", "__synthesizedOrdinal")
                                                .HasName("pk_carros");

                                            b3.ToTable("carros");

                                            b3.WithOwner()
                                                .HasForeignKey("PropriedadeScraping<decimal>ExtraCarroId", "PropriedadeScraping<decimal>Extra__synthesizedOrdinal")
                                                .HasConstraintName("fk_carros_carros_propriedade_scraping_decimal_extra_carro_id_prop");
                                        });

                                    b2.Navigation("Fontes");
                                });

                            b1.OwnsOne("APIFORD.Model.CarroClasses.PropriedadeScraping<decimal>", "CapacidadeTanque", b2 =>
                                {
                                    b2.Property<int>("ExtraCarroId");

                                    b2.Property<int>("Extra__synthesizedOrdinal");

                                    b2.Property<double>("Confianca");

                                    b2.Property<bool>("Conflito");

                                    b2.HasKey("ExtraCarroId", "Extra__synthesizedOrdinal")
                                        .HasName("pk_carros");

                                    b2.ToTable("carros");

                                    b2.WithOwner()
                                        .HasForeignKey("ExtraCarroId", "Extra__synthesizedOrdinal")
                                        .HasConstraintName("fk_carros_carros_extra_carro_id_extra__synthesized_ordinal");

                                    b2.OwnsMany("APIFORD.Model.CarroClasses.ItemFonteScraping<decimal>", "Fontes", b3 =>
                                        {
                                            b3.Property<int>("PropriedadeScraping<decimal>ExtraCarroId");

                                            b3.Property<int>("PropriedadeScraping<decimal>Extra__synthesizedOrdinal");

                                            b3.Property<int>("__synthesizedOrdinal")
                                                .ValueGeneratedOnAdd();

                                            b3.Property<double>("Confianca");

                                            b3.Property<DateTime>("DataColeta");

                                            b3.Property<DateTime?>("DataReferencia");

                                            b3.Property<string>("Fonte")
                                                .IsRequired();

                                            b3.Property<int>("FonteId");

                                            b3.Property<decimal>("Valor");

                                            b3.HasKey("PropriedadeScraping<decimal>ExtraCarroId", "PropriedadeScraping<decimal>Extra__synthesizedOrdinal", "__synthesizedOrdinal")
                                                .HasName("pk_carros");

                                            b3.ToTable("carros");

                                            b3.WithOwner()
                                                .HasForeignKey("PropriedadeScraping<decimal>ExtraCarroId", "PropriedadeScraping<decimal>Extra__synthesizedOrdinal")
                                                .HasConstraintName("fk_carros_carros_propriedade_scraping_decimal_extra_carro_id_prop");
                                        });

                                    b2.Navigation("Fontes");
                                });

                            b1.OwnsOne("APIFORD.Model.CarroClasses.PropriedadeScraping<string>", "TipoCombustivel", b2 =>
                                {
                                    b2.Property<int>("ExtraCarroId");

                                    b2.Property<int>("Extra__synthesizedOrdinal");

                                    b2.Property<double>("Confianca");

                                    b2.Property<bool>("Conflito");

                                    b2.HasKey("ExtraCarroId", "Extra__synthesizedOrdinal")
                                        .HasName("pk_carros");

                                    b2.ToTable("carros");

                                    b2.WithOwner()
                                        .HasForeignKey("ExtraCarroId", "Extra__synthesizedOrdinal")
                                        .HasConstraintName("fk_carros_carros_extra_carro_id_extra__synthesized_ordinal");

                                    b2.OwnsMany("APIFORD.Model.CarroClasses.ItemFonteScraping<string>", "Fontes", b3 =>
                                        {
                                            b3.Property<int>("PropriedadeScraping<string>ExtraCarroId");

                                            b3.Property<int>("PropriedadeScraping<string>Extra__synthesizedOrdinal");

                                            b3.Property<int>("__synthesizedOrdinal")
                                                .ValueGeneratedOnAdd();

                                            b3.Property<double>("Confianca");

                                            b3.Property<DateTime>("DataColeta");

                                            b3.Property<DateTime?>("DataReferencia");

                                            b3.Property<string>("Fonte")
                                                .IsRequired();

                                            b3.Property<int>("FonteId");

                                            b3.Property<string>("Valor");

                                            b3.HasKey("PropriedadeScraping<string>ExtraCarroId", "PropriedadeScraping<string>Extra__synthesizedOrdinal", "__synthesizedOrdinal")
                                                .HasName("pk_carros");

                                            b3.ToTable("carros");

                                            b3.WithOwner()
                                                .HasForeignKey("PropriedadeScraping<string>ExtraCarroId", "PropriedadeScraping<string>Extra__synthesizedOrdinal")
                                                .HasConstraintName("fk_carros_carros_propriedade_scraping_string_extra_carro_id_propr");
                                        });

                                    b2.Navigation("Fontes");
                                });

                            b1.Navigation("CapacidadeCarga")
                                .IsRequired();

                            b1.Navigation("CapacidadeReboque")
                                .IsRequired();

                            b1.Navigation("CapacidadeTanque")
                                .IsRequired();

                            b1.Navigation("TipoCombustivel")
                                .IsRequired();
                        });

                    b.OwnsMany("APIFORD.Model.CarroClasses.Pneu", "Pneus", b1 =>
                        {
                            b1.Property<int>("CarroId");

                            b1.Property<int>("__synthesizedOrdinal")
                                .ValueGeneratedOnAdd();

                            b1.Property<DateTime>("DataColeta");

                            b1.HasKey("CarroId", "__synthesizedOrdinal");

                            b1.ToTable("carros");

                            b1
                                .ToJson("pneus")
                                .HasColumnType("jsonb");

                            b1.WithOwner()
                                .HasForeignKey("CarroId")
                                .HasConstraintName("fk_carros_carros_carro_id");

                            b1.OwnsOne("APIFORD.Model.CarroClasses.PropriedadeScraping<int>", "Aro", b2 =>
                                {
                                    b2.Property<int>("PneuCarroId");

                                    b2.Property<int>("Pneu__synthesizedOrdinal");

                                    b2.Property<double>("Confianca");

                                    b2.Property<bool>("Conflito");

                                    b2.HasKey("PneuCarroId", "Pneu__synthesizedOrdinal")
                                        .HasName("pk_carros");

                                    b2.ToTable("carros");

                                    b2.WithOwner()
                                        .HasForeignKey("PneuCarroId", "Pneu__synthesizedOrdinal")
                                        .HasConstraintName("fk_carros_carros_pneu_carro_id_pneu__synthesized_ordinal");

                                    b2.OwnsMany("APIFORD.Model.CarroClasses.ItemFonteScraping<int>", "Fontes", b3 =>
                                        {
                                            b3.Property<int>("PropriedadeScraping<int>PneuCarroId");

                                            b3.Property<int>("PropriedadeScraping<int>Pneu__synthesizedOrdinal");

                                            b3.Property<int>("__synthesizedOrdinal")
                                                .ValueGeneratedOnAdd();

                                            b3.Property<double>("Confianca");

                                            b3.Property<DateTime>("DataColeta");

                                            b3.Property<DateTime?>("DataReferencia");

                                            b3.Property<string>("Fonte")
                                                .IsRequired();

                                            b3.Property<int>("FonteId");

                                            b3.Property<int>("Valor");

                                            b3.HasKey("PropriedadeScraping<int>PneuCarroId", "PropriedadeScraping<int>Pneu__synthesizedOrdinal", "__synthesizedOrdinal")
                                                .HasName("pk_carros");

                                            b3.ToTable("carros");

                                            b3.WithOwner()
                                                .HasForeignKey("PropriedadeScraping<int>PneuCarroId", "PropriedadeScraping<int>Pneu__synthesizedOrdinal")
                                                .HasConstraintName("fk_carros_carros_propriedade_scraping_int_pneu_carro_id_proprieda");
                                        });

                                    b2.Navigation("Fontes");
                                });

                            b1.OwnsOne("APIFORD.Model.CarroClasses.PropriedadeScraping<int>", "Largura", b2 =>
                                {
                                    b2.Property<int>("PneuCarroId");

                                    b2.Property<int>("Pneu__synthesizedOrdinal");

                                    b2.Property<double>("Confianca");

                                    b2.Property<bool>("Conflito");

                                    b2.HasKey("PneuCarroId", "Pneu__synthesizedOrdinal")
                                        .HasName("pk_carros");

                                    b2.ToTable("carros");

                                    b2.WithOwner()
                                        .HasForeignKey("PneuCarroId", "Pneu__synthesizedOrdinal")
                                        .HasConstraintName("fk_carros_carros_pneu_carro_id_pneu__synthesized_ordinal");

                                    b2.OwnsMany("APIFORD.Model.CarroClasses.ItemFonteScraping<int>", "Fontes", b3 =>
                                        {
                                            b3.Property<int>("PropriedadeScraping<int>PneuCarroId");

                                            b3.Property<int>("PropriedadeScraping<int>Pneu__synthesizedOrdinal");

                                            b3.Property<int>("__synthesizedOrdinal")
                                                .ValueGeneratedOnAdd();

                                            b3.Property<double>("Confianca");

                                            b3.Property<DateTime>("DataColeta");

                                            b3.Property<DateTime?>("DataReferencia");

                                            b3.Property<string>("Fonte")
                                                .IsRequired();

                                            b3.Property<int>("FonteId");

                                            b3.Property<int>("Valor");

                                            b3.HasKey("PropriedadeScraping<int>PneuCarroId", "PropriedadeScraping<int>Pneu__synthesizedOrdinal", "__synthesizedOrdinal")
                                                .HasName("pk_carros");

                                            b3.ToTable("carros");

                                            b3.WithOwner()
                                                .HasForeignKey("PropriedadeScraping<int>PneuCarroId", "PropriedadeScraping<int>Pneu__synthesizedOrdinal")
                                                .HasConstraintName("fk_carros_carros_propriedade_scraping_int_pneu_carro_id_proprieda");
                                        });

                                    b2.Navigation("Fontes");
                                });

                            b1.OwnsOne("APIFORD.Model.CarroClasses.PropriedadeScraping<int>", "Perfil", b2 =>
                                {
                                    b2.Property<int>("PneuCarroId");

                                    b2.Property<int>("Pneu__synthesizedOrdinal");

                                    b2.Property<double>("Confianca");

                                    b2.Property<bool>("Conflito");

                                    b2.HasKey("PneuCarroId", "Pneu__synthesizedOrdinal")
                                        .HasName("pk_carros");

                                    b2.ToTable("carros");

                                    b2.WithOwner()
                                        .HasForeignKey("PneuCarroId", "Pneu__synthesizedOrdinal")
                                        .HasConstraintName("fk_carros_carros_pneu_carro_id_pneu__synthesized_ordinal");

                                    b2.OwnsMany("APIFORD.Model.CarroClasses.ItemFonteScraping<int>", "Fontes", b3 =>
                                        {
                                            b3.Property<int>("PropriedadeScraping<int>PneuCarroId");

                                            b3.Property<int>("PropriedadeScraping<int>Pneu__synthesizedOrdinal");

                                            b3.Property<int>("__synthesizedOrdinal")
                                                .ValueGeneratedOnAdd();

                                            b3.Property<double>("Confianca");

                                            b3.Property<DateTime>("DataColeta");

                                            b3.Property<DateTime?>("DataReferencia");

                                            b3.Property<string>("Fonte")
                                                .IsRequired();

                                            b3.Property<int>("FonteId");

                                            b3.Property<int>("Valor");

                                            b3.HasKey("PropriedadeScraping<int>PneuCarroId", "PropriedadeScraping<int>Pneu__synthesizedOrdinal", "__synthesizedOrdinal")
                                                .HasName("pk_carros");

                                            b3.ToTable("carros");

                                            b3.WithOwner()
                                                .HasForeignKey("PropriedadeScraping<int>PneuCarroId", "PropriedadeScraping<int>Pneu__synthesizedOrdinal")
                                                .HasConstraintName("fk_carros_carros_propriedade_scraping_int_pneu_carro_id_proprieda");
                                        });

                                    b2.Navigation("Fontes");
                                });

                            b1.OwnsOne("APIFORD.Model.CarroClasses.PropriedadeScraping<string>", "Tipo", b2 =>
                                {
                                    b2.Property<int>("PneuCarroId");

                                    b2.Property<int>("Pneu__synthesizedOrdinal");

                                    b2.Property<double>("Confianca");

                                    b2.Property<bool>("Conflito");

                                    b2.HasKey("PneuCarroId", "Pneu__synthesizedOrdinal")
                                        .HasName("pk_carros");

                                    b2.ToTable("carros");

                                    b2.WithOwner()
                                        .HasForeignKey("PneuCarroId", "Pneu__synthesizedOrdinal")
                                        .HasConstraintName("fk_carros_carros_pneu_carro_id_pneu__synthesized_ordinal");

                                    b2.OwnsMany("APIFORD.Model.CarroClasses.ItemFonteScraping<string>", "Fontes", b3 =>
                                        {
                                            b3.Property<int>("PropriedadeScraping<string>PneuCarroId");

                                            b3.Property<int>("PropriedadeScraping<string>Pneu__synthesizedOrdinal");

                                            b3.Property<int>("__synthesizedOrdinal")
                                                .ValueGeneratedOnAdd();

                                            b3.Property<double>("Confianca");

                                            b3.Property<DateTime>("DataColeta");

                                            b3.Property<DateTime?>("DataReferencia");

                                            b3.Property<string>("Fonte")
                                                .IsRequired();

                                            b3.Property<int>("FonteId");

                                            b3.Property<string>("Valor");

                                            b3.HasKey("PropriedadeScraping<string>PneuCarroId", "PropriedadeScraping<string>Pneu__synthesizedOrdinal", "__synthesizedOrdinal")
                                                .HasName("pk_carros");

                                            b3.ToTable("carros");

                                            b3.WithOwner()
                                                .HasForeignKey("PropriedadeScraping<string>PneuCarroId", "PropriedadeScraping<string>Pneu__synthesizedOrdinal")
                                                .HasConstraintName("fk_carros_carros_propriedade_scraping_string_pneu_carro_id_propri");
                                        });

                                    b2.Navigation("Fontes");
                                });

                            b1.Navigation("Aro")
                                .IsRequired();

                            b1.Navigation("Largura")
                                .IsRequired();

                            b1.Navigation("Perfil")
                                .IsRequired();

                            b1.Navigation("Tipo")
                                .IsRequired();
                        });

                    b.OwnsOne("APIFORD.Model.CarroClasses.PropriedadeScraping<System.Collections.Generic.List<string>>", "Modos", b1 =>
                        {
                            b1.Property<int>("CarroId");

                            b1.Property<double>("Confianca");

                            b1.Property<bool>("Conflito");

                            b1.HasKey("CarroId");

                            b1.ToTable("carros");

                            b1
                                .ToJson("modos")
                                .HasColumnType("jsonb");

                            b1.WithOwner()
                                .HasForeignKey("CarroId")
                                .HasConstraintName("fk_carros_carros_id");

                            b1.OwnsMany("APIFORD.Model.CarroClasses.ItemFonteScraping<System.Collections.Generic.List<string>>", "Fontes", b2 =>
                                {
                                    b2.Property<int>("PropriedadeScrapingCarroId");

                                    b2.Property<int>("__synthesizedOrdinal")
                                        .ValueGeneratedOnAdd();

                                    b2.Property<double>("Confianca");

                                    b2.Property<DateTime>("DataColeta");

                                    b2.Property<DateTime?>("DataReferencia");

                                    b2.Property<string>("Fonte")
                                        .IsRequired();

                                    b2.Property<int>("FonteId");

                                    b2.PrimitiveCollection<string>("Valor");

                                    b2.HasKey("PropriedadeScrapingCarroId", "__synthesizedOrdinal")
                                        .HasName("pk_carros");

                                    b2.ToTable("carros");

                                    b2.WithOwner()
                                        .HasForeignKey("PropriedadeScrapingCarroId")
                                        .HasConstraintName("fk_carros_carros_propriedade_scraping_carro_id");
                                });

                            b1.Navigation("Fontes");
                        });

                    b.Navigation("Categoria")
                        .IsRequired();

                    b.Navigation("Consumos");

                    b.Navigation("Dimensoes");

                    b.Navigation("Especificacoes");

                    b.Navigation("Extras");

                    b.Navigation("Modos")
                        .IsRequired();

                    b.Navigation("Pneus");
                });

            modelBuilder.Entity("APIFORD.Model.ModeloSalvo", b =>
                {
                    b.HasOne("APIFORD.Model.CarroClasses.Carro", "Carro")
                        .WithMany("SalvoUsuario")
                        .HasForeignKey("CarroId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_modelo_salvos_carros_carro_id");

                    b.HasOne("APIFORD.Model.User", "User")
                        .WithMany("ModelosSalvos")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_modelo_salvos_users_user_id");

                    b.Navigation("Carro");

                    b.Navigation("User");
                });

            modelBuilder.Entity("APIFORD.Model.Notification.NotificacaoUsuario", b =>
                {
                    b.HasOne("APIFORD.Model.Notification.NotificacaoEvento", "Evento")
                        .WithMany("Destinatarios")
                        .HasForeignKey("NotificacaoEventoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_notificacoes_usuarios_notificacoes_eventos_notificacao_even");

                    b.Navigation("Evento");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_asp_net_role_claims_asp_net_roles_role_id");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<string>", b =>
                {
                    b.HasOne("APIFORD.Model.User", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_asp_net_user_claims_asp_net_users_user_id");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<string>", b =>
                {
                    b.HasOne("APIFORD.Model.User", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_asp_net_user_logins_asp_net_users_user_id");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_asp_net_user_roles_asp_net_roles_role_id");

                    b.HasOne("APIFORD.Model.User", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_asp_net_user_roles_asp_net_users_user_id");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<string>", b =>
                {
                    b.HasOne("APIFORD.Model.User", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_asp_net_user_tokens_asp_net_users_user_id");
                });

            modelBuilder.Entity("APIFORD.Model.CarroClasses.Carro", b =>
                {
                    b.Navigation("SalvoUsuario");
                });

            modelBuilder.Entity("APIFORD.Model.Notification.NotificacaoEvento", b =>
                {
                    b.Navigation("Destinatarios");
                });

            modelBuilder.Entity("APIFORD.Model.User", b =>
                {
                    b.Navigation("ModelosSalvos");
                });
#pragma warning restore 612, 618
        }
    }
}
