// <auto-generated />
using System;
using APIFORD.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace APIFORD.Migrations
{
    [DbContext(typeof(FordDbContext))]
    [Migration("20260611172009_mudanca de nomes2")]
    partial class mudancadenomes2
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.5")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("APIFORD.Model.CarroClasses.Carro", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("Ano")
                        .HasColumnType("int")
                        .HasColumnName("ano");

                    b.Property<bool>("Excluido")
                        .HasColumnType("bit")
                        .HasColumnName("excluido");

                    b.Property<string>("Marca")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("marca");

                    b.Property<string>("Modelo")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("modelo");

                    b.HasKey("Id")
                        .HasName("pk_carros");

                    b.ToTable("carros", (string)null);
                });

            modelBuilder.Entity("APIFORD.Model.CarroClasses.Consumo", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("CarroId")
                        .HasColumnType("int")
                        .HasColumnName("carro_id");

                    b.Property<DateTime>("DataColeta")
                        .HasColumnType("datetime2")
                        .HasColumnName("data_coleta");

                    b.Property<bool>("Excluido")
                        .HasColumnType("bit")
                        .HasColumnName("excluido");

                    b.HasKey("Id")
                        .HasName("pk_consumos");

                    b.HasIndex("CarroId")
                        .HasDatabaseName("ix_consumos_carro_id");

                    b.ToTable("consumos", (string)null);
                });

            modelBuilder.Entity("APIFORD.Model.CarroClasses.Dimensao", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("CarroId")
                        .HasColumnType("int")
                        .HasColumnName("carro_id");

                    b.Property<DateTime>("DataColeta")
                        .HasColumnType("datetime2")
                        .HasColumnName("data_coleta");

                    b.Property<bool>("Excluido")
                        .HasColumnType("bit")
                        .HasColumnName("excluido");

                    b.HasKey("Id")
                        .HasName("pk_dimensoes");

                    b.HasIndex("CarroId")
                        .HasDatabaseName("ix_dimensoes_carro_id");

                    b.ToTable("dimensoes", (string)null);
                });

            modelBuilder.Entity("APIFORD.Model.CarroClasses.Especificacao", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("CarroId")
                        .HasColumnType("int")
                        .HasColumnName("carro_id");

                    b.Property<DateTime>("DataColeta")
                        .HasColumnType("datetime2")
                        .HasColumnName("data_coleta");

                    b.Property<bool>("Excluido")
                        .HasColumnType("bit")
                        .HasColumnName("excluido");

                    b.HasKey("Id")
                        .HasName("pk_especificacoes");

                    b.HasIndex("CarroId")
                        .HasDatabaseName("ix_especificacoes_carro_id");

                    b.ToTable("especificacoes", (string)null);
                });

            modelBuilder.Entity("APIFORD.Model.CarroClasses.Extra", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("CarroId")
                        .HasColumnType("int")
                        .HasColumnName("carro_id");

                    b.Property<DateTime>("DataColeta")
                        .HasColumnType("datetime2")
                        .HasColumnName("data_coleta");

                    b.Property<bool>("Excluido")
                        .HasColumnType("bit")
                        .HasColumnName("excluido");

                    b.HasKey("Id")
                        .HasName("pk_extras");

                    b.HasIndex("CarroId")
                        .HasDatabaseName("ix_extras_carro_id");

                    b.ToTable("extras", (string)null);
                });

            modelBuilder.Entity("APIFORD.Model.CarroClasses.Fonte", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<decimal>("Confiabilidade")
                        .HasColumnType("decimal(18,2)")
                        .HasColumnName("confiabilidade");

                    b.Property<DateTime>("DataAdicao")
                        .HasColumnType("datetime2")
                        .HasColumnName("data_adicao");

                    b.Property<bool>("Excluido")
                        .HasColumnType("bit")
                        .HasColumnName("excluido");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("nome");

                    b.Property<string>("Url")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("url");

                    b.HasKey("Id")
                        .HasName("pk_fontes");

                    b.ToTable("fontes", (string)null);
                });

            modelBuilder.Entity("APIFORD.Model.CarroClasses.Intermedians.CarroModo", b =>
                {
                    b.Property<int>("CarroId")
                        .HasColumnType("int")
                        .HasColumnName("carro_id");

                    b.Property<int>("ModoId")
                        .HasColumnType("int")
                        .HasColumnName("modo_id");

                    b.HasKey("CarroId", "ModoId")
                        .HasName("pk_carro_modos");

                    b.HasIndex("ModoId")
                        .HasDatabaseName("ix_carro_modos_modo_id");

                    b.ToTable("carro_modos", (string)null);
                });

            modelBuilder.Entity("APIFORD.Model.CarroClasses.Pneu", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("CarroId")
                        .HasColumnType("int")
                        .HasColumnName("carro_id");

                    b.Property<DateTime>("DataColeta")
                        .HasColumnType("datetime2")
                        .HasColumnName("data_coleta");

                    b.Property<bool>("Excluido")
                        .HasColumnType("bit")
                        .HasColumnName("excluido");

                    b.HasKey("Id")
                        .HasName("pk_pneus");

                    b.HasIndex("CarroId")
                        .HasDatabaseName("ix_pneus_carro_id");

                    b.ToTable("pneus", (string)null);
                });

            modelBuilder.Entity("APIFORD.Model.ModeloSalvo", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("nvarchar(450)")
                        .HasColumnName("user_id");

                    b.Property<int>("CarroId")
                        .HasColumnType("int")
                        .HasColumnName("carro_id");

                    b.HasKey("UserId", "CarroId")
                        .HasName("pk_modelo_salvos");

                    b.HasIndex("CarroId")
                        .HasDatabaseName("ix_modelo_salvos_carro_id");

                    b.ToTable("modelo_salvos", (string)null);
                });

            modelBuilder.Entity("APIFORD.Model.Modo", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Tipo")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("tipo");

                    b.HasKey("Id")
                        .HasName("pk_modos");

                    b.ToTable("modos", (string)null);
                });

            modelBuilder.Entity("APIFORD.Model.Notificacao", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("DataCriacao")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasColumnName("data_criacao")
                        .HasDefaultValueSql("GETUTCDATE()");

                    b.Property<bool>("Excluido")
                        .HasColumnType("bit")
                        .HasColumnName("excluido");

                    b.Property<bool>("Lida")
                        .HasColumnType("bit")
                        .HasColumnName("lida");

                    b.Property<string>("Mensagem")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("mensagem");

                    b.Property<string>("Subtitle")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("subtitle");

                    b.Property<string>("Titulo")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("titulo");

                    b.Property<int>("Type")
                        .HasColumnType("int")
                        .HasColumnName("type");

                    b.HasKey("Id")
                        .HasName("pk_notifications");

                    b.ToTable("notifications", (string)null);
                });

            modelBuilder.Entity("APIFORD.Model.User", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(450)")
                        .HasColumnName("id");

                    b.Property<int>("AccessFailedCount")
                        .HasColumnType("int")
                        .HasColumnName("access_failed_count");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("concurrency_stamp");

                    b.Property<string>("Email")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)")
                        .HasColumnName("email");

                    b.Property<bool>("EmailConfirmed")
                        .HasColumnType("bit")
                        .HasColumnName("email_confirmed");

                    b.Property<bool>("Excluido")
                        .HasColumnType("bit")
                        .HasColumnName("excluido");

                    b.Property<bool>("LockoutEnabled")
                        .HasColumnType("bit")
                        .HasColumnName("lockout_enabled");

                    b.Property<DateTimeOffset?>("LockoutEnd")
                        .HasColumnType("datetimeoffset")
                        .HasColumnName("lockout_end");

                    b.Property<string>("NormalizedEmail")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)")
                        .HasColumnName("normalized_email");

                    b.Property<string>("NormalizedUserName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)")
                        .HasColumnName("normalized_user_name");

                    b.Property<string>("PasswordHash")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("password_hash");

                    b.Property<string>("PhoneNumber")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("phone_number");

                    b.Property<bool>("PhoneNumberConfirmed")
                        .HasColumnType("bit")
                        .HasColumnName("phone_number_confirmed");

                    b.Property<string>("SecurityStamp")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("security_stamp");

                    b.Property<bool>("TwoFactorEnabled")
                        .HasColumnType("bit")
                        .HasColumnName("two_factor_enabled");

                    b.Property<string>("UserName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)")
                        .HasColumnName("user_name");

                    b.HasKey("Id")
                        .HasName("pk_asp_net_users");

                    b.HasIndex("NormalizedEmail")
                        .HasDatabaseName("EmailIndex");

                    b.HasIndex("NormalizedUserName")
                        .IsUnique()
                        .HasDatabaseName("UserNameIndex")
                        .HasFilter("[normalized_user_name] IS NOT NULL");

                    b.ToTable("AspNetUsers", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRole", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(450)")
                        .HasColumnName("id");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("concurrency_stamp");

                    b.Property<string>("Name")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)")
                        .HasColumnName("name");

                    b.Property<string>("NormalizedName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)")
                        .HasColumnName("normalized_name");

                    b.HasKey("Id")
                        .HasName("pk_asp_net_roles");

                    b.HasIndex("NormalizedName")
                        .IsUnique()
                        .HasDatabaseName("RoleNameIndex")
                        .HasFilter("[normalized_name] IS NOT NULL");

                    b.ToTable("AspNetRoles", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<string>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ClaimType")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("claim_type");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("claim_value");

                    b.Property<string>("RoleId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)")
                        .HasColumnName("role_id");

                    b.HasKey("Id")
                        .HasName("pk_asp_net_role_claims");

                    b.HasIndex("RoleId")
                        .HasDatabaseName("ix_asp_net_role_claims_role_id");

                    b.ToTable("AspNetRoleClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<string>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ClaimType")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("claim_type");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("claim_value");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)")
                        .HasColumnName("user_id");

                    b.HasKey("Id")
                        .HasName("pk_asp_net_user_claims");

                    b.HasIndex("UserId")
                        .HasDatabaseName("ix_asp_net_user_claims_user_id");

                    b.ToTable("AspNetUserClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<string>", b =>
                {
                    b.Property<string>("LoginProvider")
                        .HasColumnType("nvarchar(450)")
                        .HasColumnName("login_provider");

                    b.Property<string>("ProviderKey")
                        .HasColumnType("nvarchar(450)")
                        .HasColumnName("provider_key");

                    b.Property<string>("ProviderDisplayName")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("provider_display_name");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)")
                        .HasColumnName("user_id");

                    b.HasKey("LoginProvider", "ProviderKey")
                        .HasName("pk_asp_net_user_logins");

                    b.HasIndex("UserId")
                        .HasDatabaseName("ix_asp_net_user_logins_user_id");

                    b.ToTable("AspNetUserLogins", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<string>", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("nvarchar(450)")
                        .HasColumnName("user_id");

                    b.Property<string>("RoleId")
                        .HasColumnType("nvarchar(450)")
                        .HasColumnName("role_id");

                    b.HasKey("UserId", "RoleId")
                        .HasName("pk_asp_net_user_roles");

                    b.HasIndex("RoleId")
                        .HasDatabaseName("ix_asp_net_user_roles_role_id");

                    b.ToTable("AspNetUserRoles", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<string>", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("nvarchar(450)")
                        .HasColumnName("user_id");

                    b.Property<string>("LoginProvider")
                        .HasColumnType("nvarchar(450)")
                        .HasColumnName("login_provider");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(450)")
                        .HasColumnName("name");

                    b.Property<string>("Value")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("value");

                    b.HasKey("UserId", "LoginProvider", "Name")
                        .HasName("pk_asp_net_user_tokens");

                    b.ToTable("AspNetUserTokens", (string)null);
                });

            modelBuilder.Entity("APIFORD.Model.CarroClasses.Consumo", b =>
                {
                    b.HasOne("APIFORD.Model.CarroClasses.Carro", "Carro")
                        .WithMany("Consumos")
                        .HasForeignKey("CarroId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_consumos_carros_carro_id");

                    b.OwnsOne("APIFORD.Model.CarroClasses.PropriedadeScraping<string>", "Cidade", b1 =>
                        {
                            b1.Property<int>("ConsumoId");

                            b1.Property<double>("Confianca");

                            b1.Property<bool>("Conflito");

                            b1.HasKey("ConsumoId");

                            b1.ToTable("consumos");

                            b1
                                .ToJson("cidade")
                                .HasColumnType("nvarchar(max)");

                            b1.WithOwner()
                                .HasForeignKey("ConsumoId")
                                .HasConstraintName("fk_consumos_consumos_id");

                            b1.OwnsMany("APIFORD.Model.CarroClasses.ItemFonteScraping<string>", "Fontes", b2 =>
                                {
                                    b2.Property<int>("PropriedadeScraping<string>ConsumoId");

                                    b2.Property<int>("__synthesizedOrdinal")
                                        .ValueGeneratedOnAddOrUpdate();

                                    b2.Property<double>("Confianca");

                                    b2.Property<DateTime>("DataColeta");

                                    b2.Property<DateTime?>("DataReferencia");

                                    b2.Property<int>("FonteId");

                                    b2.Property<string>("Fonte")
                                        .IsRequired();

                                    b2.Property<string>("Valor");

                                    b2.HasKey("PropriedadeScraping<string>ConsumoId", "__synthesizedOrdinal");

                                    b2.ToTable("consumos");

                                    b2.WithOwner()
                                        .HasForeignKey("PropriedadeScraping<string>ConsumoId")
                                        .HasConstraintName("fk_consumos_consumos_propriedade_scraping_string_consumo_id");
                                });

                            b1.Navigation("Fontes");
                        });

                    b.OwnsOne("APIFORD.Model.CarroClasses.PropriedadeScraping<string>", "Estrada", b1 =>
                        {
                            b1.Property<int>("ConsumoId");

                            b1.Property<double>("Confianca");

                            b1.Property<bool>("Conflito");

                            b1.HasKey("ConsumoId");

                            b1.ToTable("consumos");

                            b1
                                .ToJson("estrada")
                                .HasColumnType("nvarchar(max)");

                            b1.WithOwner()
                                .HasForeignKey("ConsumoId")
                                .HasConstraintName("fk_consumos_consumos_id");

                            b1.OwnsMany("APIFORD.Model.CarroClasses.ItemFonteScraping<string>", "Fontes", b2 =>
                                {
                                    b2.Property<int>("PropriedadeScraping<string>ConsumoId");

                                    b2.Property<int>("__synthesizedOrdinal")
                                        .ValueGeneratedOnAddOrUpdate();

                                    b2.Property<double>("Confianca");

                                    b2.Property<DateTime>("DataColeta");

                                    b2.Property<DateTime?>("DataReferencia");

                                    b2.Property<int>("FonteId");

                                    b2.Property<string>("Fonte")
                                        .IsRequired();

                                    b2.Property<string>("Valor");

                                    b2.HasKey("PropriedadeScraping<string>ConsumoId", "__synthesizedOrdinal");

                                    b2.ToTable("consumos");

                                    b2.WithOwner()
                                        .HasForeignKey("PropriedadeScraping<string>ConsumoId")
                                        .HasConstraintName("fk_consumos_consumos_propriedade_scraping_string_consumo_id");
                                });

                            b1.Navigation("Fontes");
                        });

                    b.Navigation("Carro");

                    b.Navigation("Cidade")
                        .IsRequired();

                    b.Navigation("Estrada")
                        .IsRequired();
                });

            modelBuilder.Entity("APIFORD.Model.CarroClasses.Dimensao", b =>
                {
                    b.HasOne("APIFORD.Model.CarroClasses.Carro", "Carro")
                        .WithMany("Dimensoes")
                        .HasForeignKey("CarroId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_dimensoes_carros_carro_id");

                    b.OwnsOne("APIFORD.Model.CarroClasses.PropriedadeScraping<decimal>", "Altura", b1 =>
                        {
                            b1.Property<int>("DimensaoId");

                            b1.Property<double>("Confianca");

                            b1.Property<bool>("Conflito");

                            b1.HasKey("DimensaoId");

                            b1.ToTable("dimensoes");

                            b1
                                .ToJson("altura")
                                .HasColumnType("nvarchar(max)");

                            b1.WithOwner()
                                .HasForeignKey("DimensaoId")
                                .HasConstraintName("fk_dimensoes_dimensoes_id");

                            b1.OwnsMany("APIFORD.Model.CarroClasses.ItemFonteScraping<decimal>", "Fontes", b2 =>
                                {
                                    b2.Property<int>("PropriedadeScraping<decimal>DimensaoId");

                                    b2.Property<int>("__synthesizedOrdinal")
                                        .ValueGeneratedOnAddOrUpdate();

                                    b2.Property<double>("Confianca");

                                    b2.Property<DateTime>("DataColeta");

                                    b2.Property<DateTime?>("DataReferencia");

                                    b2.Property<int>("FonteId");

                                    b2.Property<string>("Fonte")
                                        .IsRequired();

                                    b2.Property<decimal>("Valor");

                                    b2.HasKey("PropriedadeScraping<decimal>DimensaoId", "__synthesizedOrdinal");

                                    b2.ToTable("dimensoes");

                                    b2.WithOwner()
                                        .HasForeignKey("PropriedadeScraping<decimal>DimensaoId")
                                        .HasConstraintName("fk_dimensoes_dimensoes_propriedade_scraping_decimal_dimensao_id");
                                });

                            b1.Navigation("Fontes");
                        });

                    b.OwnsOne("PropriedadeScraping", "Comprimento", b1 =>
                        {
                            b1.Property<int>("DimensaoId");

                            b1.Property<double>("Confianca");

                            b1.Property<bool>("Conflito");

                            b1.HasKey("DimensaoId")
                                .HasName("pk_dimensoes");

                            b1.ToTable("dimensoes");

                            b1
                                .ToJson("comprimento")
                                .HasColumnType("nvarchar(max)");

                            b1.WithOwner()
                                .HasForeignKey("DimensaoId")
                                .HasConstraintName("fk_dimensoes_dimensoes_dimensao_id");

                            b1.OwnsMany("ItemFonteScraping", "Fontes", b2 =>
                                {
                                    b2.Property<int>("PropriedadeScrapingDimensaoId");

                                    b2.Property<int>("__synthesizedOrdinal")
                                        .ValueGeneratedOnAddOrUpdate();

                                    b2.Property<double>("Confianca");

                                    b2.Property<DateTime>("DataColeta");

                                    b2.Property<DateTime?>("DataReferencia");

                                    b2.Property<int>("FonteId");

                                    b2.Property<string>("Fonte")
                                        .IsRequired();

                                    b2.Property<decimal>("Valor");

                                    b2.HasKey("PropriedadeScrapingDimensaoId", "__synthesizedOrdinal")
                                        .HasName("pk_dimensoes");

                                    b2.ToTable("dimensoes");

                                    b2.WithOwner()
                                        .HasForeignKey("PropriedadeScrapingDimensaoId")
                                        .HasConstraintName("fk_dimensoes_dimensoes_propriedade_scraping_dimensao_id");
                                });

                            b1.Navigation("Fontes");
                        });

                    b.OwnsOne("APIFORD.Model.CarroClasses.PropriedadeScraping<decimal>", "EntreEixos", b1 =>
                        {
                            b1.Property<int>("DimensaoId");

                            b1.Property<double>("Confianca");

                            b1.Property<bool>("Conflito");

                            b1.HasKey("DimensaoId");

                            b1.ToTable("dimensoes");

                            b1
                                .ToJson("entre_eixos")
                                .HasColumnType("nvarchar(max)");

                            b1.WithOwner()
                                .HasForeignKey("DimensaoId")
                                .HasConstraintName("fk_dimensoes_dimensoes_id");

                            b1.OwnsMany("APIFORD.Model.CarroClasses.ItemFonteScraping<decimal>", "Fontes", b2 =>
                                {
                                    b2.Property<int>("PropriedadeScraping<decimal>DimensaoId");

                                    b2.Property<int>("__synthesizedOrdinal")
                                        .ValueGeneratedOnAddOrUpdate();

                                    b2.Property<double>("Confianca");

                                    b2.Property<DateTime>("DataColeta");

                                    b2.Property<DateTime?>("DataReferencia");

                                    b2.Property<int>("FonteId");

                                    b2.Property<string>("Fonte")
                                        .IsRequired();

                                    b2.Property<decimal>("Valor");

                                    b2.HasKey("PropriedadeScraping<decimal>DimensaoId", "__synthesizedOrdinal");

                                    b2.ToTable("dimensoes");

                                    b2.WithOwner()
                                        .HasForeignKey("PropriedadeScraping<decimal>DimensaoId")
                                        .HasConstraintName("fk_dimensoes_dimensoes_propriedade_scraping_decimal_dimensao_id");
                                });

                            b1.Navigation("Fontes");
                        });

                    b.OwnsOne("APIFORD.Model.CarroClasses.PropriedadeScraping<decimal>", "Largura", b1 =>
                        {
                            b1.Property<int>("DimensaoId");

                            b1.Property<double>("Confianca");

                            b1.Property<bool>("Conflito");

                            b1.HasKey("DimensaoId");

                            b1.ToTable("dimensoes");

                            b1
                                .ToJson("largura")
                                .HasColumnType("nvarchar(max)");

                            b1.WithOwner()
                                .HasForeignKey("DimensaoId")
                                .HasConstraintName("fk_dimensoes_dimensoes_id");

                            b1.OwnsMany("APIFORD.Model.CarroClasses.ItemFonteScraping<decimal>", "Fontes", b2 =>
                                {
                                    b2.Property<int>("PropriedadeScraping<decimal>DimensaoId");

                                    b2.Property<int>("__synthesizedOrdinal")
                                        .ValueGeneratedOnAddOrUpdate();

                                    b2.Property<double>("Confianca");

                                    b2.Property<DateTime>("DataColeta");

                                    b2.Property<DateTime?>("DataReferencia");

                                    b2.Property<int>("FonteId");

                                    b2.Property<string>("Fonte")
                                        .IsRequired();

                                    b2.Property<decimal>("Valor");

                                    b2.HasKey("PropriedadeScraping<decimal>DimensaoId", "__synthesizedOrdinal");

                                    b2.ToTable("dimensoes");

                                    b2.WithOwner()
                                        .HasForeignKey("PropriedadeScraping<decimal>DimensaoId")
                                        .HasConstraintName("fk_dimensoes_dimensoes_propriedade_scraping_decimal_dimensao_id");
                                });

                            b1.Navigation("Fontes");
                        });

                    b.Navigation("Altura")
                        .IsRequired();

                    b.Navigation("Carro");

                    b.Navigation("Comprimento")
                        .IsRequired();

                    b.Navigation("EntreEixos")
                        .IsRequired();

                    b.Navigation("Largura")
                        .IsRequired();
                });

            modelBuilder.Entity("APIFORD.Model.CarroClasses.Especificacao", b =>
                {
                    b.HasOne("APIFORD.Model.CarroClasses.Carro", "Carro")
                        .WithMany("Especificacoes")
                        .HasForeignKey("CarroId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_especificacoes_carros_carro_id");

                    b.OwnsOne("PropriedadeScraping", "Potencia", b1 =>
                        {
                            b1.Property<int>("EspecificacaoId");

                            b1.Property<double>("Confianca");

                            b1.Property<bool>("Conflito");

                            b1.HasKey("EspecificacaoId")
                                .HasName("pk_especificacoes");

                            b1.ToTable("especificacoes");

                            b1
                                .ToJson("potencia")
                                .HasColumnType("nvarchar(max)");

                            b1.WithOwner()
                                .HasForeignKey("EspecificacaoId")
                                .HasConstraintName("fk_especificacoes_especificacoes_especificacao_id");

                            b1.OwnsMany("ItemFonteScraping", "Fontes", b2 =>
                                {
                                    b2.Property<int>("PropriedadeScrapingEspecificacaoId");

                                    b2.Property<int>("__synthesizedOrdinal")
                                        .ValueGeneratedOnAddOrUpdate();

                                    b2.Property<double>("Confianca");

                                    b2.Property<DateTime>("DataColeta");

                                    b2.Property<DateTime?>("DataReferencia");

                                    b2.Property<int>("FonteId");

                                    b2.Property<string>("Fonte")
                                        .IsRequired();

                                    b2.Property<int>("Valor");

                                    b2.HasKey("PropriedadeScrapingEspecificacaoId", "__synthesizedOrdinal")
                                        .HasName("pk_especificacoes");

                                    b2.ToTable("especificacoes");

                                    b2.WithOwner()
                                        .HasForeignKey("PropriedadeScrapingEspecificacaoId")
                                        .HasConstraintName("fk_especificacoes_especificacoes_propriedade_scraping_especificacao_id");
                                });

                            b1.Navigation("Fontes");
                        });

                    b.OwnsOne("APIFORD.Model.CarroClasses.PropriedadeScraping<int>", "PotenciaRpm", b1 =>
                        {
                            b1.Property<int>("EspecificacaoId");

                            b1.Property<double>("Confianca");

                            b1.Property<bool>("Conflito");

                            b1.HasKey("EspecificacaoId");

                            b1.ToTable("especificacoes");

                            b1
                                .ToJson("potencia_rpm")
                                .HasColumnType("nvarchar(max)");

                            b1.WithOwner()
                                .HasForeignKey("EspecificacaoId")
                                .HasConstraintName("fk_especificacoes_especificacoes_id");

                            b1.OwnsMany("APIFORD.Model.CarroClasses.ItemFonteScraping<int>", "Fontes", b2 =>
                                {
                                    b2.Property<int>("PropriedadeScraping<int>EspecificacaoId");

                                    b2.Property<int>("__synthesizedOrdinal")
                                        .ValueGeneratedOnAddOrUpdate();

                                    b2.Property<double>("Confianca");

                                    b2.Property<DateTime>("DataColeta");

                                    b2.Property<DateTime?>("DataReferencia");

                                    b2.Property<int>("FonteId");

                                    b2.Property<string>("Fonte")
                                        .IsRequired();

                                    b2.Property<int>("Valor");

                                    b2.HasKey("PropriedadeScraping<int>EspecificacaoId", "__synthesizedOrdinal");

                                    b2.ToTable("especificacoes");

                                    b2.WithOwner()
                                        .HasForeignKey("PropriedadeScraping<int>EspecificacaoId")
                                        .HasConstraintName("fk_especificacoes_especificacoes_propriedade_scraping_int_especificacao_id");
                                });

                            b1.Navigation("Fontes");
                        });

                    b.OwnsOne("APIFORD.Model.CarroClasses.PropriedadeScraping<int>", "Torque", b1 =>
                        {
                            b1.Property<int>("EspecificacaoId");

                            b1.Property<double>("Confianca");

                            b1.Property<bool>("Conflito");

                            b1.HasKey("EspecificacaoId");

                            b1.ToTable("especificacoes");

                            b1
                                .ToJson("torque")
                                .HasColumnType("nvarchar(max)");

                            b1.WithOwner()
                                .HasForeignKey("EspecificacaoId")
                                .HasConstraintName("fk_especificacoes_especificacoes_id");

                            b1.OwnsMany("APIFORD.Model.CarroClasses.ItemFonteScraping<int>", "Fontes", b2 =>
                                {
                                    b2.Property<int>("PropriedadeScraping<int>EspecificacaoId");

                                    b2.Property<int>("__synthesizedOrdinal")
                                        .ValueGeneratedOnAddOrUpdate();

                                    b2.Property<double>("Confianca");

                                    b2.Property<DateTime>("DataColeta");

                                    b2.Property<DateTime?>("DataReferencia");

                                    b2.Property<int>("FonteId");

                                    b2.Property<string>("Fonte")
                                        .IsRequired();

                                    b2.Property<int>("Valor");

                                    b2.HasKey("PropriedadeScraping<int>EspecificacaoId", "__synthesizedOrdinal");

                                    b2.ToTable("especificacoes");

                                    b2.WithOwner()
                                        .HasForeignKey("PropriedadeScraping<int>EspecificacaoId")
                                        .HasConstraintName("fk_especificacoes_especificacoes_propriedade_scraping_int_especificacao_id");
                                });

                            b1.Navigation("Fontes");
                        });

                    b.OwnsOne("APIFORD.Model.CarroClasses.PropriedadeScraping<int>", "TorqueRpm", b1 =>
                        {
                            b1.Property<int>("EspecificacaoId");

                            b1.Property<double>("Confianca");

                            b1.Property<bool>("Conflito");

                            b1.HasKey("EspecificacaoId");

                            b1.ToTable("especificacoes");

                            b1
                                .ToJson("torque_rpm")
                                .HasColumnType("nvarchar(max)");

                            b1.WithOwner()
                                .HasForeignKey("EspecificacaoId")
                                .HasConstraintName("fk_especificacoes_especificacoes_id");

                            b1.OwnsMany("APIFORD.Model.CarroClasses.ItemFonteScraping<int>", "Fontes", b2 =>
                                {
                                    b2.Property<int>("PropriedadeScraping<int>EspecificacaoId");

                                    b2.Property<int>("__synthesizedOrdinal")
                                        .ValueGeneratedOnAddOrUpdate();

                                    b2.Property<double>("Confianca");

                                    b2.Property<DateTime>("DataColeta");

                                    b2.Property<DateTime?>("DataReferencia");

                                    b2.Property<int>("FonteId");

                                    b2.Property<string>("Fonte")
                                        .IsRequired();

                                    b2.Property<int>("Valor");

                                    b2.HasKey("PropriedadeScraping<int>EspecificacaoId", "__synthesizedOrdinal");

                                    b2.ToTable("especificacoes");

                                    b2.WithOwner()
                                        .HasForeignKey("PropriedadeScraping<int>EspecificacaoId")
                                        .HasConstraintName("fk_especificacoes_especificacoes_propriedade_scraping_int_especificacao_id");
                                });

                            b1.Navigation("Fontes");
                        });

                    b.OwnsOne("APIFORD.Model.CarroClasses.PropriedadeScraping<string>", "Tracao", b1 =>
                        {
                            b1.Property<int>("EspecificacaoId");

                            b1.Property<double>("Confianca");

                            b1.Property<bool>("Conflito");

                            b1.HasKey("EspecificacaoId");

                            b1.ToTable("especificacoes");

                            b1
                                .ToJson("tracao")
                                .HasColumnType("nvarchar(max)");

                            b1.WithOwner()
                                .HasForeignKey("EspecificacaoId")
                                .HasConstraintName("fk_especificacoes_especificacoes_id");

                            b1.OwnsMany("APIFORD.Model.CarroClasses.ItemFonteScraping<string>", "Fontes", b2 =>
                                {
                                    b2.Property<int>("PropriedadeScraping<string>EspecificacaoId");

                                    b2.Property<int>("__synthesizedOrdinal")
                                        .ValueGeneratedOnAddOrUpdate();

                                    b2.Property<double>("Confianca");

                                    b2.Property<DateTime>("DataColeta");

                                    b2.Property<DateTime?>("DataReferencia");

                                    b2.Property<int>("FonteId");

                                    b2.Property<string>("Fonte")
                                        .IsRequired();

                                    b2.Property<string>("Valor");

                                    b2.HasKey("PropriedadeScraping<string>EspecificacaoId", "__synthesizedOrdinal");

                                    b2.ToTable("especificacoes");

                                    b2.WithOwner()
                                        .HasForeignKey("PropriedadeScraping<string>EspecificacaoId")
                                        .HasConstraintName("fk_especificacoes_especificacoes_propriedade_scraping_string_especificacao_id");
                                });

                            b1.Navigation("Fontes");
                        });

                    b.OwnsOne("PropriedadeScraping", "Transmissao", b1 =>
                        {
                            b1.Property<int>("EspecificacaoId");

                            b1.Property<double>("Confianca");

                            b1.Property<bool>("Conflito");

                            b1.HasKey("EspecificacaoId")
                                .HasName("pk_especificacoes");

                            b1.ToTable("especificacoes");

                            b1
                                .ToJson("transmissao")
                                .HasColumnType("nvarchar(max)");

                            b1.WithOwner()
                                .HasForeignKey("EspecificacaoId")
                                .HasConstraintName("fk_especificacoes_especificacoes_especificacao_id");

                            b1.OwnsMany("ItemFonteScraping", "Fontes", b2 =>
                                {
                                    b2.Property<int>("PropriedadeScrapingEspecificacaoId");

                                    b2.Property<int>("__synthesizedOrdinal")
                                        .ValueGeneratedOnAddOrUpdate();

                                    b2.Property<double>("Confianca");

                                    b2.Property<DateTime>("DataColeta");

                                    b2.Property<DateTime?>("DataReferencia");

                                    b2.Property<int>("FonteId");

                                    b2.Property<string>("Fonte")
                                        .IsRequired();

                                    b2.Property<string>("Valor");

                                    b2.HasKey("PropriedadeScrapingEspecificacaoId", "__synthesizedOrdinal")
                                        .HasName("pk_especificacoes");

                                    b2.ToTable("especificacoes");

                                    b2.WithOwner()
                                        .HasForeignKey("PropriedadeScrapingEspecificacaoId")
                                        .HasConstraintName("fk_especificacoes_especificacoes_propriedade_scraping_especificacao_id");
                                });

                            b1.Navigation("Fontes");
                        });

                    b.Navigation("Carro");

                    b.Navigation("Potencia")
                        .IsRequired();

                    b.Navigation("PotenciaRpm")
                        .IsRequired();

                    b.Navigation("Torque")
                        .IsRequired();

                    b.Navigation("TorqueRpm")
                        .IsRequired();

                    b.Navigation("Tracao")
                        .IsRequired();

                    b.Navigation("Transmissao")
                        .IsRequired();
                });

            modelBuilder.Entity("APIFORD.Model.CarroClasses.Extra", b =>
                {
                    b.HasOne("APIFORD.Model.CarroClasses.Carro", "Carro")
                        .WithMany("Extras")
                        .HasForeignKey("CarroId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_extras_carros_carro_id");

                    b.OwnsOne("APIFORD.Model.CarroClasses.PropriedadeScraping<string>", "CapacidadeCarga", b1 =>
                        {
                            b1.Property<int>("ExtraId");

                            b1.Property<double>("Confianca");

                            b1.Property<bool>("Conflito");

                            b1.HasKey("ExtraId");

                            b1.ToTable("extras");

                            b1
                                .ToJson("capacidade_carga")
                                .HasColumnType("nvarchar(max)");

                            b1.WithOwner()
                                .HasForeignKey("ExtraId")
                                .HasConstraintName("fk_extras_extras_id");

                            b1.OwnsMany("APIFORD.Model.CarroClasses.ItemFonteScraping<string>", "Fontes", b2 =>
                                {
                                    b2.Property<int>("PropriedadeScraping<string>ExtraId");

                                    b2.Property<int>("__synthesizedOrdinal")
                                        .ValueGeneratedOnAddOrUpdate();

                                    b2.Property<double>("Confianca");

                                    b2.Property<DateTime>("DataColeta");

                                    b2.Property<DateTime?>("DataReferencia");

                                    b2.Property<int>("FonteId");

                                    b2.Property<string>("Fonte")
                                        .IsRequired();

                                    b2.Property<string>("Valor");

                                    b2.HasKey("PropriedadeScraping<string>ExtraId", "__synthesizedOrdinal");

                                    b2.ToTable("extras");

                                    b2.WithOwner()
                                        .HasForeignKey("PropriedadeScraping<string>ExtraId")
                                        .HasConstraintName("fk_extras_extras_propriedade_scraping_string_extra_id");
                                });

                            b1.Navigation("Fontes");
                        });

                    b.OwnsOne("APIFORD.Model.CarroClasses.PropriedadeScraping<string>", "CapacidadeReboque", b1 =>
                        {
                            b1.Property<int>("ExtraId");

                            b1.Property<double>("Confianca");

                            b1.Property<bool>("Conflito");

                            b1.HasKey("ExtraId");

                            b1.ToTable("extras");

                            b1
                                .ToJson("capacidade_reboque")
                                .HasColumnType("nvarchar(max)");

                            b1.WithOwner()
                                .HasForeignKey("ExtraId")
                                .HasConstraintName("fk_extras_extras_id");

                            b1.OwnsMany("APIFORD.Model.CarroClasses.ItemFonteScraping<string>", "Fontes", b2 =>
                                {
                                    b2.Property<int>("PropriedadeScraping<string>ExtraId");

                                    b2.Property<int>("__synthesizedOrdinal")
                                        .ValueGeneratedOnAddOrUpdate();

                                    b2.Property<double>("Confianca");

                                    b2.Property<DateTime>("DataColeta");

                                    b2.Property<DateTime?>("DataReferencia");

                                    b2.Property<int>("FonteId");

                                    b2.Property<string>("Fonte")
                                        .IsRequired();

                                    b2.Property<string>("Valor");

                                    b2.HasKey("PropriedadeScraping<string>ExtraId", "__synthesizedOrdinal");

                                    b2.ToTable("extras");

                                    b2.WithOwner()
                                        .HasForeignKey("PropriedadeScraping<string>ExtraId")
                                        .HasConstraintName("fk_extras_extras_propriedade_scraping_string_extra_id");
                                });

                            b1.Navigation("Fontes");
                        });

                    b.OwnsOne("APIFORD.Model.CarroClasses.PropriedadeScraping<string>", "CapacidadeTanque", b1 =>
                        {
                            b1.Property<int>("ExtraId");

                            b1.Property<double>("Confianca");

                            b1.Property<bool>("Conflito");

                            b1.HasKey("ExtraId");

                            b1.ToTable("extras");

                            b1
                                .ToJson("capacidade_tanque")
                                .HasColumnType("nvarchar(max)");

                            b1.WithOwner()
                                .HasForeignKey("ExtraId")
                                .HasConstraintName("fk_extras_extras_id");

                            b1.OwnsMany("APIFORD.Model.CarroClasses.ItemFonteScraping<string>", "Fontes", b2 =>
                                {
                                    b2.Property<int>("PropriedadeScraping<string>ExtraId");

                                    b2.Property<int>("__synthesizedOrdinal")
                                        .ValueGeneratedOnAddOrUpdate();

                                    b2.Property<double>("Confianca");

                                    b2.Property<DateTime>("DataColeta");

                                    b2.Property<DateTime?>("DataReferencia");

                                    b2.Property<int>("FonteId");

                                    b2.Property<string>("Fonte")
                                        .IsRequired();

                                    b2.Property<string>("Valor");

                                    b2.HasKey("PropriedadeScraping<string>ExtraId", "__synthesizedOrdinal");

                                    b2.ToTable("extras");

                                    b2.WithOwner()
                                        .HasForeignKey("PropriedadeScraping<string>ExtraId")
                                        .HasConstraintName("fk_extras_extras_propriedade_scraping_string_extra_id");
                                });

                            b1.Navigation("Fontes");
                        });

                    b.OwnsOne("APIFORD.Model.CarroClasses.PropriedadeScraping<string>", "TipoCombustivel", b1 =>
                        {
                            b1.Property<int>("ExtraId");

                            b1.Property<double>("Confianca");

                            b1.Property<bool>("Conflito");

                            b1.HasKey("ExtraId");

                            b1.ToTable("extras");

                            b1
                                .ToJson("tipo_combustivel")
                                .HasColumnType("nvarchar(max)");

                            b1.WithOwner()
                                .HasForeignKey("ExtraId")
                                .HasConstraintName("fk_extras_extras_id");

                            b1.OwnsMany("APIFORD.Model.CarroClasses.ItemFonteScraping<string>", "Fontes", b2 =>
                                {
                                    b2.Property<int>("PropriedadeScraping<string>ExtraId");

                                    b2.Property<int>("__synthesizedOrdinal")
                                        .ValueGeneratedOnAddOrUpdate();

                                    b2.Property<double>("Confianca");

                                    b2.Property<DateTime>("DataColeta");

                                    b2.Property<DateTime?>("DataReferencia");

                                    b2.Property<int>("FonteId");

                                    b2.Property<string>("Fonte")
                                        .IsRequired();

                                    b2.Property<string>("Valor");

                                    b2.HasKey("PropriedadeScraping<string>ExtraId", "__synthesizedOrdinal");

                                    b2.ToTable("extras");

                                    b2.WithOwner()
                                        .HasForeignKey("PropriedadeScraping<string>ExtraId")
                                        .HasConstraintName("fk_extras_extras_propriedade_scraping_string_extra_id");
                                });

                            b1.Navigation("Fontes");
                        });

                    b.Navigation("CapacidadeCarga")
                        .IsRequired();

                    b.Navigation("CapacidadeReboque")
                        .IsRequired();

                    b.Navigation("CapacidadeTanque")
                        .IsRequired();

                    b.Navigation("Carro");

                    b.Navigation("TipoCombustivel")
                        .IsRequired();
                });

            modelBuilder.Entity("APIFORD.Model.CarroClasses.Intermedians.CarroModo", b =>
                {
                    b.HasOne("APIFORD.Model.CarroClasses.Carro", "Carro")
                        .WithMany("ModosCarro")
                        .HasForeignKey("CarroId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_carro_modos_carros_carro_id");

                    b.HasOne("APIFORD.Model.Modo", "Modo")
                        .WithMany("CarroModos")
                        .HasForeignKey("ModoId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_carro_modos_modos_modo_id");

                    b.Navigation("Carro");

                    b.Navigation("Modo");
                });

            modelBuilder.Entity("APIFORD.Model.CarroClasses.Pneu", b =>
                {
                    b.HasOne("APIFORD.Model.CarroClasses.Carro", "Carro")
                        .WithMany("Pneus")
                        .HasForeignKey("CarroId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_pneus_carros_carro_id");

                    b.OwnsOne("APIFORD.Model.CarroClasses.PropriedadeScraping<int>", "Aro", b1 =>
                        {
                            b1.Property<int>("PneuId");

                            b1.Property<double>("Confianca");

                            b1.Property<bool>("Conflito");

                            b1.HasKey("PneuId");

                            b1.ToTable("pneus");

                            b1
                                .ToJson("aro")
                                .HasColumnType("nvarchar(max)");

                            b1.WithOwner()
                                .HasForeignKey("PneuId")
                                .HasConstraintName("fk_pneus_pneus_id");

                            b1.OwnsMany("APIFORD.Model.CarroClasses.ItemFonteScraping<int>", "Fontes", b2 =>
                                {
                                    b2.Property<int>("PropriedadeScraping<int>PneuId");

                                    b2.Property<int>("__synthesizedOrdinal")
                                        .ValueGeneratedOnAddOrUpdate();

                                    b2.Property<double>("Confianca");

                                    b2.Property<DateTime>("DataColeta");

                                    b2.Property<DateTime?>("DataReferencia");

                                    b2.Property<int>("FonteId");

                                    b2.Property<string>("Fonte")
                                        .IsRequired();

                                    b2.Property<int>("Valor");

                                    b2.HasKey("PropriedadeScraping<int>PneuId", "__synthesizedOrdinal");

                                    b2.ToTable("pneus");

                                    b2.WithOwner()
                                        .HasForeignKey("PropriedadeScraping<int>PneuId")
                                        .HasConstraintName("fk_pneus_pneus_propriedade_scraping_int_pneu_id");
                                });

                            b1.Navigation("Fontes");
                        });

                    b.OwnsOne("APIFORD.Model.CarroClasses.PropriedadeScraping<int>", "Largura", b1 =>
                        {
                            b1.Property<int>("PneuId");

                            b1.Property<double>("Confianca");

                            b1.Property<bool>("Conflito");

                            b1.HasKey("PneuId");

                            b1.ToTable("pneus");

                            b1
                                .ToJson("largura")
                                .HasColumnType("nvarchar(max)");

                            b1.WithOwner()
                                .HasForeignKey("PneuId")
                                .HasConstraintName("fk_pneus_pneus_id");

                            b1.OwnsMany("APIFORD.Model.CarroClasses.ItemFonteScraping<int>", "Fontes", b2 =>
                                {
                                    b2.Property<int>("PropriedadeScraping<int>PneuId");

                                    b2.Property<int>("__synthesizedOrdinal")
                                        .ValueGeneratedOnAddOrUpdate();

                                    b2.Property<double>("Confianca");

                                    b2.Property<DateTime>("DataColeta");

                                    b2.Property<DateTime?>("DataReferencia");

                                    b2.Property<int>("FonteId");

                                    b2.Property<string>("Fonte")
                                        .IsRequired();

                                    b2.Property<int>("Valor");

                                    b2.HasKey("PropriedadeScraping<int>PneuId", "__synthesizedOrdinal");

                                    b2.ToTable("pneus");

                                    b2.WithOwner()
                                        .HasForeignKey("PropriedadeScraping<int>PneuId")
                                        .HasConstraintName("fk_pneus_pneus_propriedade_scraping_int_pneu_id");
                                });

                            b1.Navigation("Fontes");
                        });

                    b.OwnsOne("APIFORD.Model.CarroClasses.PropriedadeScraping<int>", "Perfil", b1 =>
                        {
                            b1.Property<int>("PneuId");

                            b1.Property<double>("Confianca");

                            b1.Property<bool>("Conflito");

                            b1.HasKey("PneuId");

                            b1.ToTable("pneus");

                            b1
                                .ToJson("perfil")
                                .HasColumnType("nvarchar(max)");

                            b1.WithOwner()
                                .HasForeignKey("PneuId")
                                .HasConstraintName("fk_pneus_pneus_id");

                            b1.OwnsMany("APIFORD.Model.CarroClasses.ItemFonteScraping<int>", "Fontes", b2 =>
                                {
                                    b2.Property<int>("PropriedadeScraping<int>PneuId");

                                    b2.Property<int>("__synthesizedOrdinal")
                                        .ValueGeneratedOnAddOrUpdate();

                                    b2.Property<double>("Confianca");

                                    b2.Property<DateTime>("DataColeta");

                                    b2.Property<DateTime?>("DataReferencia");

                                    b2.Property<int>("FonteId");

                                    b2.Property<string>("Fonte")
                                        .IsRequired();

                                    b2.Property<int>("Valor");

                                    b2.HasKey("PropriedadeScraping<int>PneuId", "__synthesizedOrdinal");

                                    b2.ToTable("pneus");

                                    b2.WithOwner()
                                        .HasForeignKey("PropriedadeScraping<int>PneuId")
                                        .HasConstraintName("fk_pneus_pneus_propriedade_scraping_int_pneu_id");
                                });

                            b1.Navigation("Fontes");
                        });

                    b.OwnsOne("APIFORD.Model.CarroClasses.PropriedadeScraping<string>", "Tipo", b1 =>
                        {
                            b1.Property<int>("PneuId");

                            b1.Property<double>("Confianca");

                            b1.Property<bool>("Conflito");

                            b1.HasKey("PneuId");

                            b1.ToTable("pneus");

                            b1
                                .ToJson("tipo")
                                .HasColumnType("nvarchar(max)");

                            b1.WithOwner()
                                .HasForeignKey("PneuId")
                                .HasConstraintName("fk_pneus_pneus_id");

                            b1.OwnsMany("APIFORD.Model.CarroClasses.ItemFonteScraping<string>", "Fontes", b2 =>
                                {
                                    b2.Property<int>("PropriedadeScraping<string>PneuId");

                                    b2.Property<int>("__synthesizedOrdinal")
                                        .ValueGeneratedOnAddOrUpdate();

                                    b2.Property<double>("Confianca");

                                    b2.Property<DateTime>("DataColeta");

                                    b2.Property<DateTime?>("DataReferencia");

                                    b2.Property<int>("FonteId");

                                    b2.Property<string>("Fonte")
                                        .IsRequired();

                                    b2.Property<string>("Valor");

                                    b2.HasKey("PropriedadeScraping<string>PneuId", "__synthesizedOrdinal");

                                    b2.ToTable("pneus");

                                    b2.WithOwner()
                                        .HasForeignKey("PropriedadeScraping<string>PneuId")
                                        .HasConstraintName("fk_pneus_pneus_propriedade_scraping_string_pneu_id");
                                });

                            b1.Navigation("Fontes");
                        });

                    b.Navigation("Aro")
                        .IsRequired();

                    b.Navigation("Carro");

                    b.Navigation("Largura")
                        .IsRequired();

                    b.Navigation("Perfil")
                        .IsRequired();

                    b.Navigation("Tipo")
                        .IsRequired();
                });

            modelBuilder.Entity("APIFORD.Model.ModeloSalvo", b =>
                {
                    b.HasOne("APIFORD.Model.CarroClasses.Carro", "Carro")
                        .WithMany("SalvoUsuario")
                        .HasForeignKey("CarroId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_modelo_salvos_carros_carro_id");

                    b.HasOne("APIFORD.Model.User", "User")
                        .WithMany("ModelosSalvos")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_modelo_salvos_users_user_id");

                    b.Navigation("Carro");

                    b.Navigation("User");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_asp_net_role_claims_asp_net_roles_role_id");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<string>", b =>
                {
                    b.HasOne("APIFORD.Model.User", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_asp_net_user_claims_asp_net_users_user_id");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<string>", b =>
                {
                    b.HasOne("APIFORD.Model.User", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_asp_net_user_logins_asp_net_users_user_id");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_asp_net_user_roles_asp_net_roles_role_id");

                    b.HasOne("APIFORD.Model.User", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_asp_net_user_roles_asp_net_users_user_id");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<string>", b =>
                {
                    b.HasOne("APIFORD.Model.User", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_asp_net_user_tokens_asp_net_users_user_id");
                });

            modelBuilder.Entity("APIFORD.Model.CarroClasses.Carro", b =>
                {
                    b.Navigation("Consumos");

                    b.Navigation("Dimensoes");

                    b.Navigation("Especificacoes");

                    b.Navigation("Extras");

                    b.Navigation("ModosCarro");

                    b.Navigation("Pneus");

                    b.Navigation("SalvoUsuario");
                });

            modelBuilder.Entity("APIFORD.Model.Modo", b =>
                {
                    b.Navigation("CarroModos");
                });

            modelBuilder.Entity("APIFORD.Model.User", b =>
                {
                    b.Navigation("ModelosSalvos");
                });
#pragma warning restore 612, 618
        }
    }
}
