// <auto-generated />
using System;
using APIFORD.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace APIFORD.Migrations
{
    [DbContext(typeof(FordDbContext))]
    [Migration("20260501182341_Mudando forma de delete")]
    partial class Mudandoformadedelete
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.5")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("APIFORD.Model.CarroClasses.Additional", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("Carro_id")
                        .HasColumnType("int");

                    b.Property<string>("Capacidade_Tanque")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Tipo_Combustivel")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Capacidade_Carga")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Capacidade_Reboque")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("Carro_id");

                    b.ToTable("Additionals");
                });

            modelBuilder.Entity("APIFORD.Model.CarroClasses.Carro", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Brand")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Model")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Year")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("Carros");
                });

            modelBuilder.Entity("APIFORD.Model.CarroClasses.Consume", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("Carro_id")
                        .HasColumnType("int");

                    b.Property<string>("Cidade")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Estrada")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("Carro_id");

                    b.ToTable("Consumes");
                });

            modelBuilder.Entity("APIFORD.Model.CarroClasses.Dimension", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("Carro_id")
                        .HasColumnType("int");

                    b.Property<decimal>("Altura")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("Length")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("Entre_Eixos")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("Largura")
                        .HasColumnType("decimal(18,2)");

                    b.HasKey("Id");

                    b.HasIndex("Carro_id");

                    b.ToTable("Dimensions");
                });

            modelBuilder.Entity("APIFORD.Model.CarroClasses.Intermedians.AdditionalSource", b =>
                {
                    b.Property<int>("AdditionalId")
                        .HasColumnType("int");

                    b.Property<int>("SourceId")
                        .HasColumnType("int");

                    b.HasKey("AdditionalId", "SourceId");

                    b.HasIndex("SourceId");

                    b.ToTable("AdditionalSources");
                });

            modelBuilder.Entity("APIFORD.Model.CarroClasses.Intermedians.CarroMode", b =>
                {
                    b.Property<int>("Carro_id")
                        .HasColumnType("int");

                    b.Property<int>("ModeId")
                        .HasColumnType("int");

                    b.HasKey("Carro_id", "ModeId");

                    b.HasIndex("ModeId");

                    b.ToTable("CarroModes");
                });

            modelBuilder.Entity("APIFORD.Model.CarroClasses.Intermedians.ConsumeSource", b =>
                {
                    b.Property<int>("ConsumeId")
                        .HasColumnType("int");

                    b.Property<int>("SourceId")
                        .HasColumnType("int");

                    b.HasKey("ConsumeId", "SourceId");

                    b.HasIndex("SourceId");

                    b.ToTable("ConsumeSources");
                });

            modelBuilder.Entity("APIFORD.Model.CarroClasses.Intermedians.DimensionSource", b =>
                {
                    b.Property<int>("DimensionId")
                        .HasColumnType("int");

                    b.Property<int>("SourceId")
                        .HasColumnType("int");

                    b.HasKey("DimensionId", "SourceId");

                    b.HasIndex("SourceId");

                    b.ToTable("DimensionSources");
                });

            modelBuilder.Entity("APIFORD.Model.CarroClasses.Intermedians.ModeSource", b =>
                {
                    b.Property<int>("ModeId")
                        .HasColumnType("int");

                    b.Property<int>("SourceId")
                        .HasColumnType("int");

                    b.Property<int?>("ModeSourceModeId")
                        .HasColumnType("int");

                    b.Property<int?>("ModeSourceSourceId")
                        .HasColumnType("int");

                    b.HasKey("ModeId", "SourceId");

                    b.HasIndex("SourceId");

                    b.HasIndex("ModeSourceModeId", "ModeSourceSourceId");

                    b.ToTable("ModeSources");
                });

            modelBuilder.Entity("APIFORD.Model.CarroClasses.Intermedians.SpecificationSource", b =>
                {
                    b.Property<int>("SpecificationId")
                        .HasColumnType("int");

                    b.Property<int>("SourceId")
                        .HasColumnType("int");

                    b.HasKey("SpecificationId", "SourceId");

                    b.HasIndex("SourceId");

                    b.ToTable("SpecificationSources");
                });

            modelBuilder.Entity("APIFORD.Model.CarroClasses.Intermedians.TireSource", b =>
                {
                    b.Property<int>("TireId")
                        .HasColumnType("int");

                    b.Property<int>("SourceId")
                        .HasColumnType("int");

                    b.HasKey("TireId", "SourceId");

                    b.HasIndex("SourceId");

                    b.ToTable("TireSources");
                });

            modelBuilder.Entity("APIFORD.Model.CarroClasses.Source", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int?>("Carro_id")
                        .HasColumnType("int");

                    b.Property<DateTime>("DataColeta")
                        .HasColumnType("datetime2");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal>("Reliability")
                        .HasColumnType("decimal(18,2)");

                    b.HasKey("Id");

                    b.HasIndex("Carro_id");

                    b.ToTable("Sources");
                });

            modelBuilder.Entity("APIFORD.Model.CarroClasses.Specification", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("Carro_id")
                        .HasColumnType("int");

                    b.Property<string>("Potencia")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Rpm_potencia")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Rpm_torque")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Torque")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Tracao")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Transmissao")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("Carro_id");

                    b.ToTable("Specifications");
                });

            modelBuilder.Entity("APIFORD.Model.CarroClasses.Tire", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("Carro_id")
                        .HasColumnType("int");

                    b.Property<int>("Perfil")
                        .HasColumnType("int");

                    b.Property<int>("Aro")
                        .HasColumnType("int");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Largura")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("Carro_id");

                    b.ToTable("Tires");
                });

            modelBuilder.Entity("APIFORD.Model.Mode", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Modes");
                });

            modelBuilder.Entity("APIFORD.Model.Notification", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreationTime")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("GETUTCDATE()");

                    b.Property<string>("Mensagem")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("Read")
                        .HasColumnType("bit");

                    b.Property<string>("Subtitle")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Type")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("Notifications");
                });

            modelBuilder.Entity("APIFORD.Model.SavedModel", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<int>("Carro_id")
                        .HasColumnType("int");

                    b.HasKey("UserId", "Carro_id");

                    b.HasIndex("Carro_id");

                    b.ToTable("SavedModels");
                });

            modelBuilder.Entity("APIFORD.Model.User", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<int>("AccessFailedCount")
                        .HasColumnType("int");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Email")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<bool>("EmailConfirmed")
                        .HasColumnType("bit");

                    b.Property<bool>("LockoutEnabled")
                        .HasColumnType("bit");

                    b.Property<DateTimeOffset?>("LockoutEnd")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("NormalizedEmail")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("NormalizedUserName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("PasswordHash")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PhoneNumber")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("PhoneNumberConfirmed")
                        .HasColumnType("bit");

                    b.Property<string>("SecurityStamp")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("TwoFactorEnabled")
                        .HasColumnType("bit");

                    b.Property<string>("UserName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedEmail")
                        .HasDatabaseName("EmailIndex");

                    b.HasIndex("NormalizedUserName")
                        .IsUnique()
                        .HasDatabaseName("UserNameIndex")
                        .HasFilter("[NormalizedUserName] IS NOT NULL");

                    b.ToTable("AspNetUsers", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRole", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("NormalizedName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedName")
                        .IsUnique()
                        .HasDatabaseName("RoleNameIndex")
                        .HasFilter("[NormalizedName] IS NOT NULL");

                    b.ToTable("AspNetRoles", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<string>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ClaimType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("RoleId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetRoleClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<string>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ClaimType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<string>", b =>
                {
                    b.Property<string>("LoginProvider")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ProviderKey")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ProviderDisplayName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("LoginProvider", "ProviderKey");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserLogins", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<string>", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("RoleId")
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("UserId", "RoleId");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetUserRoles", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<string>", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("LoginProvider")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Value")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("UserId", "LoginProvider", "Name");

                    b.ToTable("AspNetUserTokens", (string)null);
                });

            modelBuilder.Entity("APIFORD.Model.CarroClasses.Additional", b =>
                {
                    b.HasOne("APIFORD.Model.CarroClasses.Carro", null)
                        .WithMany("Additionals")
                        .HasForeignKey("Carro_id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("APIFORD.Model.CarroClasses.Consume", b =>
                {
                    b.HasOne("APIFORD.Model.CarroClasses.Carro", null)
                        .WithMany("Consumes")
                        .HasForeignKey("Carro_id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("APIFORD.Model.CarroClasses.Dimension", b =>
                {
                    b.HasOne("APIFORD.Model.CarroClasses.Carro", null)
                        .WithMany("Dimensions")
                        .HasForeignKey("Carro_id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("APIFORD.Model.CarroClasses.Intermedians.AdditionalSource", b =>
                {
                    b.HasOne("APIFORD.Model.CarroClasses.Additional", "Additional")
                        .WithMany("AdditionalSources")
                        .HasForeignKey("AdditionalId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("APIFORD.Model.CarroClasses.Source", "Source")
                        .WithMany("AdditionalSources")
                        .HasForeignKey("SourceId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Additional");

                    b.Navigation("Source");
                });

            modelBuilder.Entity("APIFORD.Model.CarroClasses.Intermedians.CarroMode", b =>
                {
                    b.HasOne("APIFORD.Model.CarroClasses.Carro", "Carro")
                        .WithMany("CarroModes")
                        .HasForeignKey("Carro_id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("APIFORD.Model.Mode", "Mode")
                        .WithMany("CarroModes")
                        .HasForeignKey("ModeId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Carro");

                    b.Navigation("Mode");
                });

            modelBuilder.Entity("APIFORD.Model.CarroClasses.Intermedians.ConsumeSource", b =>
                {
                    b.HasOne("APIFORD.Model.CarroClasses.Consume", "Consume")
                        .WithMany("ConsumeSources")
                        .HasForeignKey("ConsumeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("APIFORD.Model.CarroClasses.Source", "Source")
                        .WithMany("ConsumeSources")
                        .HasForeignKey("SourceId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Consume");

                    b.Navigation("Source");
                });

            modelBuilder.Entity("APIFORD.Model.CarroClasses.Intermedians.DimensionSource", b =>
                {
                    b.HasOne("APIFORD.Model.CarroClasses.Dimension", "Dimension")
                        .WithMany("DimensionSources")
                        .HasForeignKey("DimensionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("APIFORD.Model.CarroClasses.Source", "Source")
                        .WithMany("DimensionSources")
                        .HasForeignKey("SourceId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Dimension");

                    b.Navigation("Source");
                });

            modelBuilder.Entity("APIFORD.Model.CarroClasses.Intermedians.ModeSource", b =>
                {
                    b.HasOne("APIFORD.Model.Mode", "Mode")
                        .WithMany("ModeSources")
                        .HasForeignKey("ModeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("APIFORD.Model.CarroClasses.Source", "Source")
                        .WithMany("ModeSources")
                        .HasForeignKey("SourceId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("APIFORD.Model.CarroClasses.Intermedians.ModeSource", null)
                        .WithMany("ModeSources")
                        .HasForeignKey("ModeSourceModeId", "ModeSourceSourceId");

                    b.Navigation("Mode");

                    b.Navigation("Source");
                });

            modelBuilder.Entity("APIFORD.Model.CarroClasses.Intermedians.SpecificationSource", b =>
                {
                    b.HasOne("APIFORD.Model.CarroClasses.Source", "Source")
                        .WithMany("SpecificationSources")
                        .HasForeignKey("SourceId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("APIFORD.Model.CarroClasses.Specification", "Specification")
                        .WithMany("SpecificationSources")
                        .HasForeignKey("SpecificationId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Source");

                    b.Navigation("Specification");
                });

            modelBuilder.Entity("APIFORD.Model.CarroClasses.Intermedians.TireSource", b =>
                {
                    b.HasOne("APIFORD.Model.CarroClasses.Source", "Source")
                        .WithMany("TireSources")
                        .HasForeignKey("SourceId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("APIFORD.Model.CarroClasses.Tire", "Tire")
                        .WithMany("TireSources")
                        .HasForeignKey("TireId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Source");

                    b.Navigation("Tire");
                });

            modelBuilder.Entity("APIFORD.Model.CarroClasses.Source", b =>
                {
                    b.HasOne("APIFORD.Model.CarroClasses.Carro", null)
                        .WithMany("Sources")
                        .HasForeignKey("Carro_id");
                });

            modelBuilder.Entity("APIFORD.Model.CarroClasses.Specification", b =>
                {
                    b.HasOne("APIFORD.Model.CarroClasses.Carro", "Carro")
                        .WithMany("Specifications")
                        .HasForeignKey("Carro_id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Carro");
                });

            modelBuilder.Entity("APIFORD.Model.CarroClasses.Tire", b =>
                {
                    b.HasOne("APIFORD.Model.CarroClasses.Carro", null)
                        .WithMany("Tires")
                        .HasForeignKey("Carro_id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("APIFORD.Model.SavedModel", b =>
                {
                    b.HasOne("APIFORD.Model.CarroClasses.Carro", "Carro")
                        .WithMany("UsersSave")
                        .HasForeignKey("Carro_id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("APIFORD.Model.User", "User")
                        .WithMany("SavedModels")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Carro");

                    b.Navigation("User");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<string>", b =>
                {
                    b.HasOne("APIFORD.Model.User", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<string>", b =>
                {
                    b.HasOne("APIFORD.Model.User", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("APIFORD.Model.User", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<string>", b =>
                {
                    b.HasOne("APIFORD.Model.User", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("APIFORD.Model.CarroClasses.Additional", b =>
                {
                    b.Navigation("AdditionalSources");
                });

            modelBuilder.Entity("APIFORD.Model.CarroClasses.Carro", b =>
                {
                    b.Navigation("Additionals");

                    b.Navigation("CarroModes");

                    b.Navigation("Consumes");

                    b.Navigation("Dimensions");

                    b.Navigation("Sources");

                    b.Navigation("Specifications");

                    b.Navigation("Tires");

                    b.Navigation("UsersSave");
                });

            modelBuilder.Entity("APIFORD.Model.CarroClasses.Consume", b =>
                {
                    b.Navigation("ConsumeSources");
                });

            modelBuilder.Entity("APIFORD.Model.CarroClasses.Dimension", b =>
                {
                    b.Navigation("DimensionSources");
                });

            modelBuilder.Entity("APIFORD.Model.CarroClasses.Intermedians.ModeSource", b =>
                {
                    b.Navigation("ModeSources");
                });

            modelBuilder.Entity("APIFORD.Model.CarroClasses.Source", b =>
                {
                    b.Navigation("AdditionalSources");

                    b.Navigation("ConsumeSources");

                    b.Navigation("DimensionSources");

                    b.Navigation("ModeSources");

                    b.Navigation("SpecificationSources");

                    b.Navigation("TireSources");
                });

            modelBuilder.Entity("APIFORD.Model.CarroClasses.Specification", b =>
                {
                    b.Navigation("SpecificationSources");
                });

            modelBuilder.Entity("APIFORD.Model.CarroClasses.Tire", b =>
                {
                    b.Navigation("TireSources");
                });

            modelBuilder.Entity("APIFORD.Model.Mode", b =>
                {
                    b.Navigation("CarroModes");

                    b.Navigation("ModeSources");
                });

            modelBuilder.Entity("APIFORD.Model.User", b =>
                {
                    b.Navigation("SavedModels");
                });
#pragma warning restore 612, 618
        }
    }
}
