// <auto-generated />
using System;
using APIFORD.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace APIFORD.Migrations
{
    [DbContext(typeof(FordDbContext))]
    partial class UserDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.5")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("APIFORD.Model.CarroClasses.Carro", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("Ano")
                        .HasColumnType("int")
                        .HasColumnName("ano");

                    b.Property<bool>("Excluido")
                        .HasColumnType("bit")
                        .HasColumnName("excluido");

                    b.Property<string>("Marca")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("marca");

                    b.Property<string>("Modelo")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("modelo");

                    b.HasKey("Id")
                        .HasName("pk_carros");

                    b.ToTable("carros", (string)null);
                });

            modelBuilder.Entity("APIFORD.Model.CarroClasses.Consumo", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("CarroId")
                        .HasColumnType("int")
                        .HasColumnName("carro_id");

                    b.Property<string>("Cidade")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("cidade");

                    b.Property<string>("Estrada")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("estrada");

                    b.Property<bool>("Excluido")
                        .HasColumnType("bit")
                        .HasColumnName("excluido");

                    b.HasKey("Id")
                        .HasName("pk_consumos");

                    b.HasIndex("CarroId")
                        .HasDatabaseName("ix_consumos_carro_id");

                    b.ToTable("consumos", (string)null);
                });

            modelBuilder.Entity("APIFORD.Model.CarroClasses.Dimensao", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<decimal>("Altura")
                        .HasColumnType("decimal(18,2)")
                        .HasColumnName("altura");

                    b.Property<int>("CarroId")
                        .HasColumnType("int")
                        .HasColumnName("carro_id");

                    b.Property<decimal>("Comprimento")
                        .HasColumnType("decimal(18,2)")
                        .HasColumnName("comprimento");

                    b.Property<decimal>("EntreEixos")
                        .HasColumnType("decimal(18,2)")
                        .HasColumnName("entre_eixos");

                    b.Property<bool>("Excluido")
                        .HasColumnType("bit")
                        .HasColumnName("excluido");

                    b.Property<decimal>("Largura")
                        .HasColumnType("decimal(18,2)")
                        .HasColumnName("largura");

                    b.HasKey("Id")
                        .HasName("pk_dimensoes");

                    b.HasIndex("CarroId")
                        .HasDatabaseName("ix_dimensoes_carro_id");

                    b.ToTable("dimensoes", (string)null);
                });

            modelBuilder.Entity("APIFORD.Model.CarroClasses.Especificacao", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("CarroId")
                        .HasColumnType("int")
                        .HasColumnName("carro_id");

                    b.Property<bool>("Excluido")
                        .HasColumnType("bit")
                        .HasColumnName("excluido");

                    b.Property<int>("Potencia")
                        .HasColumnType("int")
                        .HasColumnName("potencia");

                    b.Property<int>("RpmPotencia")
                        .HasColumnType("int")
                        .HasColumnName("rpm_potencia");

                    b.Property<int>("RpmTorque")
                        .HasColumnType("int")
                        .HasColumnName("rpm_torque");

                    b.Property<int>("Torque")
                        .HasColumnType("int")
                        .HasColumnName("torque");

                    b.Property<string>("Tracao")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("tracao");

                    b.Property<string>("Transmissao")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("transmissao");

                    b.HasKey("Id")
                        .HasName("pk_especificacoes");

                    b.HasIndex("CarroId")
                        .HasDatabaseName("ix_especificacoes_carro_id");

                    b.ToTable("especificacoes", (string)null);
                });

            modelBuilder.Entity("APIFORD.Model.CarroClasses.Extra", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("CapacidadeCarga")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("capacidade_carga");

                    b.Property<string>("CapacidadeReboque")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("capacidade_reboque");

                    b.Property<string>("CapacidadeTanque")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("capacidade_tanque");

                    b.Property<int>("CarroId")
                        .HasColumnType("int")
                        .HasColumnName("carro_id");

                    b.Property<bool>("Excluido")
                        .HasColumnType("bit")
                        .HasColumnName("excluido");

                    b.Property<string>("TipoCombustivel")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("tipo_combustivel");

                    b.HasKey("Id")
                        .HasName("pk_extras");

                    b.HasIndex("CarroId")
                        .HasDatabaseName("ix_extras_carro_id");

                    b.ToTable("extras", (string)null);
                });

            modelBuilder.Entity("APIFORD.Model.CarroClasses.Fonte", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<decimal>("Confiabilidade")
                        .HasColumnType("decimal(18,2)")
                        .HasColumnName("confiabilidade");

                    b.Property<DateTime>("DataAdicao")
                        .HasColumnType("datetime2")
                        .HasColumnName("data_adicao");

                    b.Property<bool>("Excluido")
                        .HasColumnType("bit")
                        .HasColumnName("excluido");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("nome");

                    b.HasKey("Id")
                        .HasName("pk_fontes");

                    b.ToTable("fontes", (string)null);
                });

            modelBuilder.Entity("APIFORD.Model.CarroClasses.Intermedians.CarroModo", b =>
                {
                    b.Property<int>("CarroId")
                        .HasColumnType("int")
                        .HasColumnName("carro_id");

                    b.Property<int>("ModoId")
                        .HasColumnType("int")
                        .HasColumnName("modo_id");

                    b.HasKey("CarroId", "ModoId")
                        .HasName("pk_carro_modos");

                    b.HasIndex("ModoId")
                        .HasDatabaseName("ix_carro_modos_modo_id");

                    b.ToTable("carro_modos", (string)null);
                });

            modelBuilder.Entity("APIFORD.Model.CarroClasses.Intermedians.ConsumoFonte", b =>
                {
                    b.Property<int>("ConsumoId")
                        .HasColumnType("int")
                        .HasColumnName("consumo_id");

                    b.Property<int>("FonteId")
                        .HasColumnType("int")
                        .HasColumnName("fonte_id");

                    b.Property<DateTime>("DataColeta")
                        .HasColumnType("datetime2")
                        .HasColumnName("data_coleta");

                    b.Property<DateTime?>("DataReferencia")
                        .HasColumnType("datetime2")
                        .HasColumnName("data_referencia");

                    b.HasKey("ConsumoId", "FonteId")
                        .HasName("pk_consumo_fontes");

                    b.HasIndex("FonteId")
                        .HasDatabaseName("ix_consumo_fontes_fonte_id");

                    b.ToTable("consumo_fontes", (string)null);
                });

            modelBuilder.Entity("APIFORD.Model.CarroClasses.Intermedians.DimensaoFonte", b =>
                {
                    b.Property<int>("DimensaoId")
                        .HasColumnType("int")
                        .HasColumnName("dimensao_id");

                    b.Property<int>("FonteId")
                        .HasColumnType("int")
                        .HasColumnName("fonte_id");

                    b.Property<DateTime>("DataColeta")
                        .HasColumnType("datetime2")
                        .HasColumnName("data_coleta");

                    b.Property<DateTime?>("DataReferencia")
                        .HasColumnType("datetime2")
                        .HasColumnName("data_referencia");

                    b.HasKey("DimensaoId", "FonteId")
                        .HasName("pk_dimensao_fontes");

                    b.HasIndex("FonteId")
                        .HasDatabaseName("ix_dimensao_fontes_fonte_id");

                    b.ToTable("dimensao_fontes", (string)null);
                });

            modelBuilder.Entity("APIFORD.Model.CarroClasses.Intermedians.EspecificacaoFonte", b =>
                {
                    b.Property<int>("EspecificacaoId")
                        .HasColumnType("int")
                        .HasColumnName("especificacao_id");

                    b.Property<int>("FonteId")
                        .HasColumnType("int")
                        .HasColumnName("fonte_id");

                    b.Property<DateTime>("DataColeta")
                        .HasColumnType("datetime2")
                        .HasColumnName("data_coleta");

                    b.Property<DateTime?>("DataReferencia")
                        .HasColumnType("datetime2")
                        .HasColumnName("data_referencia");

                    b.HasKey("EspecificacaoId", "FonteId")
                        .HasName("pk_especificacao_fontes");

                    b.HasIndex("FonteId")
                        .HasDatabaseName("ix_especificacao_fontes_fonte_id");

                    b.ToTable("especificacao_fontes", (string)null);
                });

            modelBuilder.Entity("APIFORD.Model.CarroClasses.Intermedians.ExtraFonte", b =>
                {
                    b.Property<int>("ExtraId")
                        .HasColumnType("int")
                        .HasColumnName("extra_id");

                    b.Property<int>("FonteId")
                        .HasColumnType("int")
                        .HasColumnName("fonte_id");

                    b.Property<DateTime>("DataColeta")
                        .HasColumnType("datetime2")
                        .HasColumnName("data_coleta");

                    b.Property<DateTime?>("DataReferencia")
                        .HasColumnType("datetime2")
                        .HasColumnName("data_referencia");

                    b.HasKey("ExtraId", "FonteId")
                        .HasName("pk_extra_fontes");

                    b.HasIndex("FonteId")
                        .HasDatabaseName("ix_extra_fontes_fonte_id");

                    b.ToTable("extra_fontes", (string)null);
                });

            modelBuilder.Entity("APIFORD.Model.CarroClasses.Intermedians.ModoFonte", b =>
                {
                    b.Property<int>("ModoId")
                        .HasColumnType("int")
                        .HasColumnName("modo_id");

                    b.Property<int>("FonteId")
                        .HasColumnType("int")
                        .HasColumnName("fonte_id");

                    b.Property<DateTime>("DataColeta")
                        .HasColumnType("datetime2")
                        .HasColumnName("data_coleta");

                    b.Property<DateTime?>("DataReferencia")
                        .HasColumnType("datetime2")
                        .HasColumnName("data_referencia");

                    b.Property<int?>("ModoFonteFonteId")
                        .HasColumnType("int")
                        .HasColumnName("modo_fonte_fonte_id");

                    b.Property<int?>("ModoFonteModoId")
                        .HasColumnType("int")
                        .HasColumnName("modo_fonte_modo_id");

                    b.HasKey("ModoId", "FonteId")
                        .HasName("pk_modo_fontes");

                    b.HasIndex("FonteId")
                        .HasDatabaseName("ix_modo_fontes_fonte_id");

                    b.HasIndex("ModoFonteModoId", "ModoFonteFonteId")
                        .HasDatabaseName("ix_modo_fontes_modo_fonte_modo_id_modo_fonte_fonte_id");

                    b.ToTable("modo_fontes", (string)null);
                });

            modelBuilder.Entity("APIFORD.Model.CarroClasses.Intermedians.PneuFonte", b =>
                {
                    b.Property<int>("PneuId")
                        .HasColumnType("int")
                        .HasColumnName("pneu_id");

                    b.Property<int>("FonteId")
                        .HasColumnType("int")
                        .HasColumnName("fonte_id");

                    b.Property<DateTime>("DataColeta")
                        .HasColumnType("datetime2")
                        .HasColumnName("data_coleta");

                    b.Property<DateTime?>("DataReferencia")
                        .HasColumnType("datetime2")
                        .HasColumnName("data_referencia");

                    b.HasKey("PneuId", "FonteId")
                        .HasName("pk_pneu_fontes");

                    b.HasIndex("FonteId")
                        .HasDatabaseName("ix_pneu_fontes_fonte_id");

                    b.ToTable("pneu_fontes", (string)null);
                });

            modelBuilder.Entity("APIFORD.Model.CarroClasses.Pneu", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("Aro")
                        .HasColumnType("int")
                        .HasColumnName("aro");

                    b.Property<int>("CarroId")
                        .HasColumnType("int")
                        .HasColumnName("carro_id");

                    b.Property<bool>("Excluido")
                        .HasColumnType("bit")
                        .HasColumnName("excluido");

                    b.Property<int>("Largura")
                        .HasColumnType("int")
                        .HasColumnName("largura");

                    b.Property<int>("Perfil")
                        .HasColumnType("int")
                        .HasColumnName("perfil");

                    b.Property<string>("Tipo")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("tipo");

                    b.HasKey("Id")
                        .HasName("pk_pneus");

                    b.HasIndex("CarroId")
                        .HasDatabaseName("ix_pneus_carro_id");

                    b.ToTable("pneus", (string)null);
                });

            modelBuilder.Entity("APIFORD.Model.ModeloSalvo", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("nvarchar(450)")
                        .HasColumnName("user_id");

                    b.Property<int>("CarroId")
                        .HasColumnType("int")
                        .HasColumnName("carro_id");

                    b.HasKey("UserId", "CarroId")
                        .HasName("pk_modelo_salvos");

                    b.HasIndex("CarroId")
                        .HasDatabaseName("ix_modelo_salvos_carro_id");

                    b.ToTable("modelo_salvos", (string)null);
                });

            modelBuilder.Entity("APIFORD.Model.Modo", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Tipo")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("tipo");

                    b.HasKey("Id")
                        .HasName("pk_modos");

                    b.ToTable("modos", (string)null);
                });

            modelBuilder.Entity("APIFORD.Model.Notificacao", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("DataCriacao")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasColumnName("data_criacao")
                        .HasDefaultValueSql("GETUTCDATE()");

                    b.Property<bool>("Excluido")
                        .HasColumnType("bit")
                        .HasColumnName("excluido");

                    b.Property<bool>("Lida")
                        .HasColumnType("bit")
                        .HasColumnName("lida");

                    b.Property<string>("Mensagem")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("mensagem");

                    b.Property<string>("Subtitle")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("subtitle");

                    b.Property<string>("Titulo")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("titulo");

                    b.Property<int>("Type")
                        .HasColumnType("int")
                        .HasColumnName("type");

                    b.HasKey("Id")
                        .HasName("pk_notifications");

                    b.ToTable("notifications", (string)null);
                });

            modelBuilder.Entity("APIFORD.Model.User", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(450)")
                        .HasColumnName("id");

                    b.Property<int>("AccessFailedCount")
                        .HasColumnType("int")
                        .HasColumnName("access_failed_count");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("concurrency_stamp");

                    b.Property<string>("Email")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)")
                        .HasColumnName("email");

                    b.Property<bool>("EmailConfirmed")
                        .HasColumnType("bit")
                        .HasColumnName("email_confirmed");

                    b.Property<bool>("Excluido")
                        .HasColumnType("bit")
                        .HasColumnName("excluido");

                    b.Property<bool>("LockoutEnabled")
                        .HasColumnType("bit")
                        .HasColumnName("lockout_enabled");

                    b.Property<DateTimeOffset?>("LockoutEnd")
                        .HasColumnType("datetimeoffset")
                        .HasColumnName("lockout_end");

                    b.Property<string>("NormalizedEmail")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)")
                        .HasColumnName("normalized_email");

                    b.Property<string>("NormalizedUserName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)")
                        .HasColumnName("normalized_user_name");

                    b.Property<string>("PasswordHash")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("password_hash");

                    b.Property<string>("PhoneNumber")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("phone_number");

                    b.Property<bool>("PhoneNumberConfirmed")
                        .HasColumnType("bit")
                        .HasColumnName("phone_number_confirmed");

                    b.Property<string>("SecurityStamp")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("security_stamp");

                    b.Property<bool>("TwoFactorEnabled")
                        .HasColumnType("bit")
                        .HasColumnName("two_factor_enabled");

                    b.Property<string>("UserName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)")
                        .HasColumnName("user_name");

                    b.HasKey("Id")
                        .HasName("pk_asp_net_users");

                    b.HasIndex("NormalizedEmail")
                        .HasDatabaseName("EmailIndex");

                    b.HasIndex("NormalizedUserName")
                        .IsUnique()
                        .HasDatabaseName("UserNameIndex")
                        .HasFilter("[normalized_user_name] IS NOT NULL");

                    b.ToTable("AspNetUsers", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRole", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(450)")
                        .HasColumnName("id");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("concurrency_stamp");

                    b.Property<string>("Name")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)")
                        .HasColumnName("name");

                    b.Property<string>("NormalizedName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)")
                        .HasColumnName("normalized_name");

                    b.HasKey("Id")
                        .HasName("pk_asp_net_roles");

                    b.HasIndex("NormalizedName")
                        .IsUnique()
                        .HasDatabaseName("RoleNameIndex")
                        .HasFilter("[normalized_name] IS NOT NULL");

                    b.ToTable("AspNetRoles", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<string>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ClaimType")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("claim_type");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("claim_value");

                    b.Property<string>("RoleId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)")
                        .HasColumnName("role_id");

                    b.HasKey("Id")
                        .HasName("pk_asp_net_role_claims");

                    b.HasIndex("RoleId")
                        .HasDatabaseName("ix_asp_net_role_claims_role_id");

                    b.ToTable("AspNetRoleClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<string>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ClaimType")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("claim_type");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("claim_value");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)")
                        .HasColumnName("user_id");

                    b.HasKey("Id")
                        .HasName("pk_asp_net_user_claims");

                    b.HasIndex("UserId")
                        .HasDatabaseName("ix_asp_net_user_claims_user_id");

                    b.ToTable("AspNetUserClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<string>", b =>
                {
                    b.Property<string>("LoginProvider")
                        .HasColumnType("nvarchar(450)")
                        .HasColumnName("login_provider");

                    b.Property<string>("ProviderKey")
                        .HasColumnType("nvarchar(450)")
                        .HasColumnName("provider_key");

                    b.Property<string>("ProviderDisplayName")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("provider_display_name");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)")
                        .HasColumnName("user_id");

                    b.HasKey("LoginProvider", "ProviderKey")
                        .HasName("pk_asp_net_user_logins");

                    b.HasIndex("UserId")
                        .HasDatabaseName("ix_asp_net_user_logins_user_id");

                    b.ToTable("AspNetUserLogins", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<string>", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("nvarchar(450)")
                        .HasColumnName("user_id");

                    b.Property<string>("RoleId")
                        .HasColumnType("nvarchar(450)")
                        .HasColumnName("role_id");

                    b.HasKey("UserId", "RoleId")
                        .HasName("pk_asp_net_user_roles");

                    b.HasIndex("RoleId")
                        .HasDatabaseName("ix_asp_net_user_roles_role_id");

                    b.ToTable("AspNetUserRoles", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<string>", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("nvarchar(450)")
                        .HasColumnName("user_id");

                    b.Property<string>("LoginProvider")
                        .HasColumnType("nvarchar(450)")
                        .HasColumnName("login_provider");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(450)")
                        .HasColumnName("name");

                    b.Property<string>("Value")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("value");

                    b.HasKey("UserId", "LoginProvider", "Name")
                        .HasName("pk_asp_net_user_tokens");

                    b.ToTable("AspNetUserTokens", (string)null);
                });

            modelBuilder.Entity("APIFORD.Model.CarroClasses.Consumo", b =>
                {
                    b.HasOne("APIFORD.Model.CarroClasses.Carro", null)
                        .WithMany("Consumos")
                        .HasForeignKey("CarroId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_consumos_carros_carro_id");
                });

            modelBuilder.Entity("APIFORD.Model.CarroClasses.Dimensao", b =>
                {
                    b.HasOne("APIFORD.Model.CarroClasses.Carro", null)
                        .WithMany("Dimensoes")
                        .HasForeignKey("CarroId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_dimensoes_carros_carro_id");
                });

            modelBuilder.Entity("APIFORD.Model.CarroClasses.Especificacao", b =>
                {
                    b.HasOne("APIFORD.Model.CarroClasses.Carro", "Carro")
                        .WithMany("Especificacaos")
                        .HasForeignKey("CarroId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_especificacoes_carros_carro_id");

                    b.Navigation("Carro");
                });

            modelBuilder.Entity("APIFORD.Model.CarroClasses.Extra", b =>
                {
                    b.HasOne("APIFORD.Model.CarroClasses.Carro", null)
                        .WithMany("Extras")
                        .HasForeignKey("CarroId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_extras_carros_carro_id");
                });

            modelBuilder.Entity("APIFORD.Model.CarroClasses.Intermedians.CarroModo", b =>
                {
                    b.HasOne("APIFORD.Model.CarroClasses.Carro", "Carro")
                        .WithMany("ModosCarro")
                        .HasForeignKey("CarroId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_carro_modos_carros_carro_id");

                    b.HasOne("APIFORD.Model.Modo", "Modo")
                        .WithMany("CarroModos")
                        .HasForeignKey("ModoId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_carro_modos_modos_modo_id");

                    b.Navigation("Carro");

                    b.Navigation("Modo");
                });

            modelBuilder.Entity("APIFORD.Model.CarroClasses.Intermedians.ConsumoFonte", b =>
                {
                    b.HasOne("APIFORD.Model.CarroClasses.Consumo", "Consumo")
                        .WithMany("ConsumoFontes")
                        .HasForeignKey("ConsumoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_consumo_fontes_consumos_consumo_id");

                    b.HasOne("APIFORD.Model.CarroClasses.Fonte", "Fonte")
                        .WithMany("ConsumoFontes")
                        .HasForeignKey("FonteId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_consumo_fontes_fontes_fonte_id");

                    b.Navigation("Consumo");

                    b.Navigation("Fonte");
                });

            modelBuilder.Entity("APIFORD.Model.CarroClasses.Intermedians.DimensaoFonte", b =>
                {
                    b.HasOne("APIFORD.Model.CarroClasses.Dimensao", "Dimensao")
                        .WithMany("DimensaoFontes")
                        .HasForeignKey("DimensaoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_dimensao_fontes_dimensoes_dimensao_id");

                    b.HasOne("APIFORD.Model.CarroClasses.Fonte", "Fonte")
                        .WithMany("DimensaoFontes")
                        .HasForeignKey("FonteId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_dimensao_fontes_fontes_fonte_id");

                    b.Navigation("Dimensao");

                    b.Navigation("Fonte");
                });

            modelBuilder.Entity("APIFORD.Model.CarroClasses.Intermedians.EspecificacaoFonte", b =>
                {
                    b.HasOne("APIFORD.Model.CarroClasses.Especificacao", "Especificacao")
                        .WithMany("EspecificacaoFontes")
                        .HasForeignKey("EspecificacaoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_especificacao_fontes_especificacoes_especificacao_id");

                    b.HasOne("APIFORD.Model.CarroClasses.Fonte", "Fonte")
                        .WithMany("EspecificacaoFontes")
                        .HasForeignKey("FonteId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_especificacao_fontes_fontes_fonte_id");

                    b.Navigation("Especificacao");

                    b.Navigation("Fonte");
                });

            modelBuilder.Entity("APIFORD.Model.CarroClasses.Intermedians.ExtraFonte", b =>
                {
                    b.HasOne("APIFORD.Model.CarroClasses.Extra", "Extra")
                        .WithMany("ExtraFontes")
                        .HasForeignKey("ExtraId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_extra_fontes_extras_extra_id");

                    b.HasOne("APIFORD.Model.CarroClasses.Fonte", "Fonte")
                        .WithMany("ExtraFontes")
                        .HasForeignKey("FonteId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_extra_fontes_fontes_fonte_id");

                    b.Navigation("Extra");

                    b.Navigation("Fonte");
                });

            modelBuilder.Entity("APIFORD.Model.CarroClasses.Intermedians.ModoFonte", b =>
                {
                    b.HasOne("APIFORD.Model.CarroClasses.Fonte", "Fonte")
                        .WithMany("ModoFontes")
                        .HasForeignKey("FonteId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_modo_fontes_fontes_fonte_id");

                    b.HasOne("APIFORD.Model.Modo", "Modo")
                        .WithMany("ModoFontes")
                        .HasForeignKey("ModoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_modo_fontes_modos_modo_id");

                    b.HasOne("APIFORD.Model.CarroClasses.Intermedians.ModoFonte", null)
                        .WithMany("FontesModo")
                        .HasForeignKey("ModoFonteModoId", "ModoFonteFonteId")
                        .HasConstraintName("fk_modo_fontes_modo_fontes_modo_fonte_modo_id_modo_fonte_fonte_id");

                    b.Navigation("Fonte");

                    b.Navigation("Modo");
                });

            modelBuilder.Entity("APIFORD.Model.CarroClasses.Intermedians.PneuFonte", b =>
                {
                    b.HasOne("APIFORD.Model.CarroClasses.Fonte", "Fonte")
                        .WithMany("PneuFontes")
                        .HasForeignKey("FonteId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_pneu_fontes_fontes_fonte_id");

                    b.HasOne("APIFORD.Model.CarroClasses.Pneu", "Pneu")
                        .WithMany("PneuFontes")
                        .HasForeignKey("PneuId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_pneu_fontes_pneus_pneu_id");

                    b.Navigation("Fonte");

                    b.Navigation("Pneu");
                });

            modelBuilder.Entity("APIFORD.Model.CarroClasses.Pneu", b =>
                {
                    b.HasOne("APIFORD.Model.CarroClasses.Carro", null)
                        .WithMany("Pneus")
                        .HasForeignKey("CarroId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_pneus_carros_carro_id");
                });

            modelBuilder.Entity("APIFORD.Model.ModeloSalvo", b =>
                {
                    b.HasOne("APIFORD.Model.CarroClasses.Carro", "Carro")
                        .WithMany("SalvoUsuario")
                        .HasForeignKey("CarroId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_modelo_salvos_carros_carro_id");

                    b.HasOne("APIFORD.Model.User", "User")
                        .WithMany("ModelosSalvos")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_modelo_salvos_users_user_id");

                    b.Navigation("Carro");

                    b.Navigation("User");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_asp_net_role_claims_asp_net_roles_role_id");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<string>", b =>
                {
                    b.HasOne("APIFORD.Model.User", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_asp_net_user_claims_asp_net_users_user_id");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<string>", b =>
                {
                    b.HasOne("APIFORD.Model.User", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_asp_net_user_logins_asp_net_users_user_id");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_asp_net_user_roles_asp_net_roles_role_id");

                    b.HasOne("APIFORD.Model.User", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_asp_net_user_roles_asp_net_users_user_id");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<string>", b =>
                {
                    b.HasOne("APIFORD.Model.User", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_asp_net_user_tokens_asp_net_users_user_id");
                });

            modelBuilder.Entity("APIFORD.Model.CarroClasses.Carro", b =>
                {
                    b.Navigation("Consumos");

                    b.Navigation("Dimensoes");

                    b.Navigation("Especificacaos");

                    b.Navigation("Extras");

                    b.Navigation("ModosCarro");

                    b.Navigation("Pneus");

                    b.Navigation("SalvoUsuario");
                });

            modelBuilder.Entity("APIFORD.Model.CarroClasses.Consumo", b =>
                {
                    b.Navigation("ConsumoFontes");
                });

            modelBuilder.Entity("APIFORD.Model.CarroClasses.Dimensao", b =>
                {
                    b.Navigation("DimensaoFontes");
                });

            modelBuilder.Entity("APIFORD.Model.CarroClasses.Especificacao", b =>
                {
                    b.Navigation("EspecificacaoFontes");
                });

            modelBuilder.Entity("APIFORD.Model.CarroClasses.Extra", b =>
                {
                    b.Navigation("ExtraFontes");
                });

            modelBuilder.Entity("APIFORD.Model.CarroClasses.Fonte", b =>
                {
                    b.Navigation("ConsumoFontes");

                    b.Navigation("DimensaoFontes");

                    b.Navigation("EspecificacaoFontes");

                    b.Navigation("ExtraFontes");

                    b.Navigation("ModoFontes");

                    b.Navigation("PneuFontes");
                });

            modelBuilder.Entity("APIFORD.Model.CarroClasses.Intermedians.ModoFonte", b =>
                {
                    b.Navigation("FontesModo");
                });

            modelBuilder.Entity("APIFORD.Model.CarroClasses.Pneu", b =>
                {
                    b.Navigation("PneuFontes");
                });

            modelBuilder.Entity("APIFORD.Model.Modo", b =>
                {
                    b.Navigation("CarroModos");

                    b.Navigation("ModoFontes");
                });

            modelBuilder.Entity("APIFORD.Model.User", b =>
                {
                    b.Navigation("ModelosSalvos");
                });
#pragma warning restore 612, 618
        }
    }
}
